### ISSUE TITLE
Proxy Host > HTTP only to Windows Web Server > Certify the Web

### ISSUE THREAD

**Issue by maieredv-manuel** [ZoeyVid/NPMplus#1017]
Hello again :-)

after switching from "Classic" NPM to NPMPlus i have a second strange Problem.
I have 3 Proxyhosts set with HTTP Only that are pointing directly to one of my Servers.
On that Server are running some Services that arent direktly HTTP related (SMTP Server for example).
But there Services also need Certificates, so i order and renew them via Certify the  Web.

Now i have on one of those Hosts the problem that the renewal isnt working anymore, when i navigate to the Path were the Files are places, i get an Error 404 from NPMPlus and not from the Server itselfs.

**Comment by Zoey2936** [comment]
what path do you mean?

**Comment by maieredv-manuel** [comment]
Ah, sorry ....
domainname.de/.well-known/acme-challenge 
/.well-known connects to the right Server 
 /.well-known/acme-challenge comes back from NPMPlus

**Comment by Zoey2936** [comment]
yes, they are used by npmplus, otherwise certbot would not work (it seems like it is broken in vanilla npm, thats why it is working for you on vanilla, normally it wouldn't work there too)
