### ISSUE TITLE
Crowdsec, bouncer only

### ISSUE THREAD

**Issue by danielholm** [ZoeyVid/NPMplus#1071]
Hi and thank you for a very nice fork. After migration it seem to work flawlessly.

I was wondering if a short guide of setting up a Crowdsec bouncer only, could be added?
I got it setup after a bit of work - in my case I had different path's than in the guide. But is it needed to add the crowdsec container or is the bouncer already part of the npmplus image?

**Comment by Zoey2936** [comment]
Hi,
crowdsec has two parts:
itself and bouncers.
NPMplus itself only contains the bouncer.
Bouncers only ask the the local ip of crowdsec itself if an external ip should be blocked or not and if yes, it blocks it
Crowdsec itself provides this local api and parses logs to see which ips are bad and should be blocked.
The Readme provides a compose which sets up crowdsec itself with configuration to parse npmplus logs
