### ISSUE TITLE
Local DNS Rewrite failing

### ISSUE THREAD

**Issue by cmar7945** [ZoeyVid/NPMplus#1099]
was able to set *.homelab rewritten to the IP of my NPM instance via my DNS server, and i could have something like adguard.homelab proxy host set up to forward http://IP:PORT. it worked with no issue on NPM. but I cant seem to do that in NPMPlus it seems to redirect to the congratulations page. What am I doing wrong? this is for internal use only, no external access.

**Comment by Zoey2936** [comment]
Even if you do this request using curl?

**Comment by cmar7945** [comment]
With npm it just worked with no issue no need to do anything extra. Just rewrote the wildcard *.homelab with my npm instance as destination and it worked for all 23 hosts. With this one I always get the congrats page except for npm.homelab which returns correctly. You ask about doing this request with curl. Which host should I run the command on?

**Comment by Zoey2936** [comment]
One of your choice, can you show me the list of your proxy hosts?

**Comment by cmar7945** [comment]
adguard.homelab -> http://192.168.0.4:8081

See above for an example of one single host. I'm not at my pc rn to give the full list.

**Comment by Zoey2936** [comment]
Just send a Screenshot when you can

**Comment by cmar7945** [comment]
Did you want the original NPM screenshot or both NPM+ and original?

**Comment by Zoey2936** [comment]
Npmplus is enough

**Comment by cmar7945** [comment]
![image](https://github.com/user-attachments/assets/0d8092d6-fec0-43fc-b41f-a4ea1d91558f)

**Comment by Zoey2936** [comment]
Can you maybe send me theier config file from /opt/npm/nginx/proxy_hosts, please?

**Comment by cmar7945** [comment]
![image](https://github.com/user-attachments/assets/aec3fa73-4b79-4f2d-afae-bab96a7890c4)

**Comment by Zoey2936** [comment]
what happens if you execute `curl -vL http://unifi.homelab` ?

**Comment by cmar7945** [comment]
Could not resolve hostname unifi.homelab

**Comment by Zoey2936** [comment]
did you configured your nameserver correctly?

**Comment by cmar7945** [comment]
All of my network is designed to look at my adguard home instance for DNS

**Comment by Zoey2936** [comment]
then it would at least be able to resolve dns, which it can not, as you can read yourself.
you can also try it on windows, you maybe need to replace curl with curl.exe

**Comment by cmar7945** [comment]
Is there a better way in npm plus to do this? Im mainly using it to make local records in a sense. Most of these services I don't want exposed to the Internet as I use unifi teleport VPN to access my site securely

**Comment by Zoey2936** [comment]
please run the curl commands otherwise I can't debug why it is not working

**Comment by cmar7945** [comment]
```
* Host unifi.homelab:80 was resolved.
* IPv6: (none)
* IPv4: 192.168.0.5
*   Trying 192.168.0.5:80...
* Connected to unifi.homelab (192.168.0.5) port 80
> GET / HTTP/1.1
> Host: unifi.homelab
> User-Agent: curl/8.8.0
> Accept: */*
>
* Request completely sent off
< HTTP/1.1 301 Moved Permanently
< Date: Fri, 20 Sep 2024 04:02:11 GMT
< Content-Type: text/html
< Content-Length: 162
< Connection: keep-alive
< Location: https://unifi.homelab/
<
* Ignoring the response-body
* Connection #0 to host unifi.homelab left intact
* Clear auth, redirects to port from 80 to 443
* Issue another request to this URL: 'https://unifi.homelab/'
* Host unifi.homelab:443 was resolved.
* IPv6: (none)
* IPv4: 192.168.0.5
*   Trying 192.168.0.5:443...
* Connected to unifi.homelab (192.168.0.5) port 443
* schannel: disabled automatic use of client certificate
* ALPN: curl offers http/1.1
* schannel: SEC_E_UNTRUSTED_ROOT (0x80090325) - The certificate chain was issued by an authority that is not trusted.
* Closing connection
* schannel: shutting down SSL/TLS connection with unifi.homelab port 443
curl: (60) schannel: SEC_E_UNTRUSTED_ROOT (0x80090325) - The certificate chain was issued by an authority that is not trusted.
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

**Comment by cmar7945** [comment]
I think the main issue is that all of the *.homelab stuff is being directed to NPM+ but not being routed to the true destination somehow.

**Comment by Zoey2936** [comment]
ok it seems for some reason to return a redirect to https, I will try reproduce it latert today

**Comment by cmar7945** [comment]
Thanks! keep me posted :)

**Comment by Zoey2936** [comment]
can you maybe send me your entire /opt/npm/nginx folder please? as a zip file maybe? to see which configuration could be the problem. since I can't reproduce it. And your compose file please

**Comment by cmar7945** [comment]
[nginx.zip](https://github.com/user-attachments/files/17083138/nginx.zip)
[npmplus.txt](https://github.com/user-attachments/files/17083141/npmplus.txt)

**Comment by cmar7945** [comment]
Please see the uploaded files for the information you requested :)

**Comment by Zoey2936** [comment]
I've created a new NPMplus and pasted your configs in, created dns rewrites and it worked. No redirect to https
