### ISSUE TITLE
How Do I Return 444 And Drop Connections for Clients of Hosts not in ACL CIDR Range? If it’s not possible, I submit it as a feature request.

### ISSUE THREAD

**Issue by charlestephen** [ZoeyVid/NPMplus#1101]
I have a server that currently functions as my Plex Media Server which I share with others and thus has some ports open to the world. I also secure all of my internal services with TLS termination using a combination of Acme.sh and NPMPlus. Despite the advanced configs with CrowdSec and ModSec, I’m still getting hit with thousands of attempts daily trying to either scan my network (which I’m ok with) or pull credentials/do SQL injection and I’ve noticed it slows down my main server significantly.

I cut down by half the attempts by securing a ZeroSSL certificate for my IP address and importing it to NPMPlus as a redirection host. Now anyone calling my IP address is automagically offloaded to Google. While that has significantly improved my server, I’d load, I’d like to do more both for energy and security sake.

Basically, I don’t want hosts on Access Lists to return 401, 403, or 404 error data to clients not matching the CIDR ranges. I just want to issue a 444 and drop the connection. This has the benefit of not informing the client why or if it’s requests would have returned legitimate results, thus cutting down on people constantly pinging my firewall.

One way I’ve figured out how to get this work is putting the following in the the http_top.conf file:

`location /  {
        allow 192.168.0.0/16;
        deny all;
        return 444;
    }`

But this seems to apply the rule to all hosts. Is there a way to be more selecting?  If I do custom location (not an advanced configuration), with that same information, should it work or will I simply break NPMPlus? I haven’t had luck and have tried this on multiple hosts. Am I missing some combination of a custom default page and a 404 redirection host or something that achieves this? Or is the only way to do it to add individual configs and I’m doing it wrong?

If it’s currently not possible, I’d like to suggest it as a feature request: return 444 and drop connection for clients not in the CIDR ranges of hosts with access lists.

**Comment by Zoey2936** [comment]
`location /  { allow 192.168.0.0/16; deny all; return 444; }`
does this not basically mean: return 403 for all connection except it is from 192.168.0.0/16 then instead drop the connection?

**Comment by Zoey2936** [comment]
also it should crash:
http_top.conf mean it is inside the http directive, but location can not be in http, only server or location: https://nginx.org/en/docs/http/ngx_http_core_module.html#location

**Comment by Zoey2936** [comment]
sorry, but I think it is not possible with nginx to change the response code from 403 to something else. if you want you can write an email to the freenginx mailing list and ask if they can add this as an option
