### ISSUE TITLE
Certbot Fails, Reports That My IP is 0.0.0.0 on a DNS Challenge

### ISSUE THREAD

**Issue by charlestephen** [ZoeyVid/NPMplus#1109]
[certbot.log](https://github.com/user-attachments/files/17091396/certbot.log)

I’m having an interesting failure where this is saying my client IP address is 0.0.0.0, thus the issuance fails. I’ve already spoken to Namecheap, and they said without the API call that Certbot issued, they really can’t troubleshoot beyond that since it’s not their product. While I understand that you didn’t make Certbot, I’m wondering if you changed anything in the package in the last few days that would have changed this behavior?

**Comment by Zoey2936** [comment]
So it works now?

**Comment by charlestephen** [comment]
Yep. It was an issue with my configuration of my Podman machine.
