### ISSUE TITLE
custom domain for npmplus dashboard

### ISSUE THREAD

**Issue by leon1995** [ZoeyVid/NPMplus#1120]
Hi,

I have setup a cusotm domain, e.g. `npmplus.mydomain.tld`, but when I want to make a change (e.g. a PUT request) then I get a 403 error back.
I forwarded `npmplus.mydomain.tld` to the https://<ip>:81. This worked with the normal npm. Do I need to configure something else?

**Comment by Zoey2936** [comment]
Modsec needs to be off
