### ISSUE TITLE
Can't setup internal location block nor use them in custom locations

### ISSUE THREAD

**Issue by parasiteoflife** [ZoeyVid/NPMplus#1136]
I'm setting up an internal location block for a proxy host using the "Advanced" tab, but any time this is done the dashboard shows the proxy host as "Offline" and no conf file is created.

```
location @handle_response {
    set $content_type $upstream_http_content_type;
    if ($content_type ~* "application/xml|application/json") {
        return 200;
    }
    return 404; 
}
```

Same happens if inside a custom location we enter

```
proxy_intercept_errors on;
error_page 200 = @handle_response;
```

**Comment by Zoey2936** [comment]
docker logs?
