### ISSUE TITLE
NPMplus can't connect to itself?

### ISSUE THREAD

**Issue by YeapGuy** [ZoeyVid/NPMplus#1183]
Hi,
After updating from the August build to latest, I can't log in to the admin dashboard. The response code I see in the browser console is 502, with no further information. Docker container logs contain this:
```
2024/10/23 12:20:16 [error] 1694#1694: *28 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.10.2, server: _, request: "POST /api/tokens HTTP/2.0", upstream: "http://127.0.0.1:48693/tokens", host: "192.168.0.11:81", referrer: "https://192.168.0.11:81/login"
```
It seems like NPMplus can't connect to its own internal API..?

**Comment by Zoey2936** [comment]
can you restart the container? since I can't reproduce it
