### ISSUE TITLE
MISSING Failure 

### ISSUE THREAD

**Issue by shedowe19** [ZoeyVid/NPMplus#1200]
![Screenshot 2024-10-31 152612](https://github.com/user-attachments/assets/4f6304e9-f8f7-482b-a1dd-e84b67afa615)
![Screenshot 2024-10-31 152625](https://github.com/user-attachments/assets/78bf2c55-9939-4379-b195-1c7e502f0308)
![Screenshot 2024-10-31 152645](https://github.com/user-attachments/assets/c700d6cd-a65e-4127-8a1f-a6b6d2369aca)
Here are the Strings Failure on German Language

**Comment by Zoey2936** [comment]
should be fixed now, please retry

**Comment by shedowe19** [comment]
![Screenshot 2024-10-31 164649](https://github.com/user-attachments/assets/404168cd-0d7c-43bd-af9c-28cf09d25152)
![Screenshot 2024-10-31 164701](https://github.com/user-attachments/assets/c0b6499a-6527-4bb3-b3a3-f3a8b4df48c9)
Nope

**Comment by shedowe19** [comment]
And another Problem are: `2024/10/31 16:31:55 [error] 1502#1502: *49 recv() failed (104: Connection reset by peer) while proxying and reading from upstream, client: 222.132.26.60, server: 0.0.0.0:3389, upstream: "10.1.16.2:3389", bytes from/to client:1164/1593, bytes from/to upstream:1593/1164
2024/10/31 16:32:10 [error] 1461#1461: *54 recv() failed (104: Connection reset by peer) while proxying and reading from upstream, client: 222.132.26.60, server: 0.0.0.0:3389, upstream: "10.1.16.2:3389", bytes from/to client:1164/1593, bytes from/to upstream:1593/1164
2024/10/31 16:32:31 [error] 1530#1530: *68 recv() failed (104: Connection reset by peer) while proxying and reading from upstream, client: 218.62.129.200, server: 0.0.0.0:3389, upstream: "10.1.16.2:3389", bytes from/to client:1164/1593, bytes from/to upstream:1593/1164
2024/10/31 16:32:40 [error] 1614#1614: *76 recv() failed (104: Connection reset by peer) while proxying and reading from upstream, client: 49.247.175.100, server: 0.0.0.0:3389, upstream: "10.1.16.2:3389", bytes from/to client:1160/1593, bytes from/to upstream:1593/1160
2024/10/31 16:32:49 [error] 1699#1699: *80 recv() failed (104: Connection reset by peer) while proxying and reading from upstream, client: 49.247.175.100, server: 0.0.0.0:3389, upstream: "10.1.16.2:3389", bytes from/to client:1144/1593, bytes from/to upstream:1593/1144
2024/10/31 16:32:50 [error] 1336#1336: *82 recv() failed (104: Connection reset by peer) while proxying and reading from upstream, client: 218.62.129.200, server: 0.0.0.0:3389, upstream: "10.1.16.2:3389", bytes from/to client:1164/1593, bytes from/to upstream:1593/1164
2024/10/31 16:32:54 [error] 1336#1336: *95 recv() failed (104: Connection reset by peer) while proxying and reading from upstream, client: 147.45.112.17, server: 0.0.0.0:3389, upstream: "10.1.16.2:3389", bytes from/to client:1178/1578, bytes from/to upstream:1578/1178
2024/10/31 16:32:55 [error] 1336#1336: *98 recv() failed (104: Connection reset by peer) while proxying and reading from upstream, client: 147.45.112.17, server: 0.0.0.0:3389, upstream: "10.1.16.2:3389", bytes from/to client:1198/1578, bytes from/to upstream:1578/1198`

**Comment by Zoey2936** [comment]
pleas test again
