### ISSUE TITLE
Error when trying to edit Stream Host

### ISSUE THREAD

**Issue by charlestephen** [ZoeyVid/NPMplus#1209]
Screenshot attached. No idea why it's doing this. I ended up simply deleting and re-adding the stream host.
![Screenshot 2024-11-02 at 2 17 03 PM](https://github.com/user-attachments/assets/c5e0aed1-0b2d-472f-bb23-b030532f3b4a)

**Comment by Zoey2936** [comment]
should be fixed with https://github.com/ZoeyVid/NPMplus/commit/ce89cf04bf12fdebba9749a7be1955cabdd31ad2, can you maybe pull the develop tag in a few minutes and try again with it?

**Comment by charlestephen** [comment]
Will do.
