### ISSUE TITLE
Missing GoAccess Errors

### ISSUE THREAD

**Issue by charlestephen** [ZoeyVid/NPMplus#1211]
I'm getting hundreds of missing GoAccess errors that are really piling up. See below:
```
/usr/local/bin/launch.sh: line 79: goaccess: not found

/usr/local/bin/launch.sh: line 79: goaccess: not found

/usr/local/bin/launch.sh: line 79: goaccess: not found

/usr/local/bin/launch.sh: line 79: goaccess: not found

/usr/local/bin/launch.sh: line 79: goaccess: not found

/usr/local/bin/launch.sh: line 79: goaccess: not found

/usr/local/bin/launch.sh: line 79: goaccess: not found
```

No further context is provided. My logs are full with this as far back as I can go and relaunching the container doesn't seem to abate it. The container is working, however. Just raising the issue in case you weren't aware.

**Comment by Zoey2936** [comment]
compose.yaml?

**Comment by charlestephen** [comment]
This randomly stopped happening after I updated an unrelated env variable on the container and relaunched it. I'll keep you updated.

**Comment by Zoey2936** [comment]
may I ask which env it was?

**Comment by charlestephen** [comment]
I'm not quite sure as I updated several at once. But the ones I updated were the `GOA_PORT` and  `GOACLA` along with the network configuration (changing from bridge to host networking).
