### ISSUE TITLE
Editing Proxy Hosts after update Docker Image got Internal Error and Proxy got Unknown stage

### ISSUE THREAD

**Issue by dathtd119** [ZoeyVid/NPMplus#1218]
After few updates automatically via Watchtower, when I edit a proxy, I got something like this:
![image](https://github.com/user-attachments/assets/ce8bbb30-2a47-462f-b060-d14f1eab2476)
![image](https://github.com/user-attachments/assets/a40b5f26-abfb-460a-a1db-44332b3b4d91)

Going through Log right after that, I found this:

`nginx: configuration file /usr/local/nginx/conf/nginx.conf test failed`

`2024/11/06 13:47:53 [error] 135277#135277: *95381 connect() failed (111: Connection refused) while connecting to upstream, client: IP, server: *my proxy A*, request: "GET /dns-query HTTP/1.1", upstream: "https://172.30.0.8:443/dns-query", host: "*my proxy B*"`

`2024/11/06 13:48:18 [error] 135277#135277: *95459 connect() failed (111: Connection refused) while connecting to upstream, client: IP, server: *my proxy A*, request: "GET /dns-query HTTP/1.1", upstream: "https://172.30.0.8:443/dns-query", host: "*my proxy B*"`

`2024/11/06 13:48:21 [error] 135277#135277: *95459 connect() failed (111: Connection refused) while connecting to upstream, client: IP, server: *my proxy A*, request: "GET /dns-query HTTP/1.1", upstream: "https://172.30.0.8:443/dns-query", host: "*my proxy A*" `

_**Known that I ran a Adguard Home DNS Image for this, and I have 2 Proxy that proxied to this image**_

**Comment by Zoey2936** [comment]
watchtower does not update npmplus, please update by hand

**Comment by dathtd119** [comment]
So how can I resolve the current problem? Backup my data then rerun the NPMplus or else?

**Comment by Zoey2936** [comment]
what version do you currently run?

**Comment by dathtd119** [comment]
I'm currently seeing the **2.12.1+5c1b2f8 version** on the NPMPlus page.
I use **zoeyvid/npmplus:latest tag** as the main version of the image, should I use a stable version?

**Comment by Zoey2936** [comment]
can you please updated to the latest release, try again and send me the full docker logs, please?

**Comment by Zoey2936** [comment]
latest tag is correct

**Comment by dathtd119** [comment]
After re-pull the latest image, everything back to normal, I can edit hosts without error. Thanks for supporting me, you guys mad fast, that's crazy 🙏🙏🙏.

By the way please make a new note or add into the compose file that make watchtower ignore update for npmplus please 😭

**Comment by Zoey2936** [comment]
I added a note to the readme

**Comment by dathtd119** [comment]
Thanks for that, appreciate the efforts 🙏🙏🙏🙏

**Comment by TheDuffman85** [comment]
> watchtower does not update npmplus, please update by hand

This is because the Docker file contains a label that sets  Watchtower to monitor-only mode. Why is that? 

https://github.com/ZoeyVid/NPMplus/blob/6165c1662d25526706166e187e036254b207f57f/Dockerfile#L117

**Comment by Zoey2936** [comment]
watchtower just "copies" all envs, this breaks NPMplus
