### ISSUE TITLE
 How to Configure NPMPLUS to Reverse Proxy Itself?

### ISSUE THREAD

**Issue by ansible34** [ZoeyVid/NPMplus#1228]
Hi,

I’m trying to set up NPMPLUS to reverse proxy itself so that I can access the web interface securely via a custom domain name (e.g., https://npm-plus.mydomain.com). However, I’m having trouble getting this configuration to work correctly.

I’ve tried setting up a proxy host with the following settings:

    Scheme: http
    Forward Hostname/IP: 127.0.0.1
    Forward Port: 81 (since the web interface runs on port 81)
    SSL: Enabled using my wildcard certificate

Despite these settings, I keep encountering SSL warnings or issues with the web interface not loading properly. Could you please provide guidance or best practices on how to configure NPMPLUS to proxy itself effectively?

Thank you for your help!

Let me know if this captures what you want to ask or if you'd like to modify anything.

**Comment by Zoey2936** [comment]
you need to use https as Scheme
