### ISSUE TITLE
Always get this error on first try

### ISSUE THREAD

**Issue by Felitendo** [ZoeyVid/NPMplus#1251]
When I try to access any site that is proxied through NPMplus, I get this error when using firefox:

MOZILLA_PKIX_ERROR_REQUIRED_TLS_FEATURE_MISSING
![grafik](https://github.com/user-attachments/assets/0f5cfe45-adb9-4f14-930f-aa61826c00a1)

I only get it with Firefox, but both on PC and on mobile.
If I refresh the site, it works just fine. It's pretty annoying though, because someone who isn't aware of this might leave the website, because they think it's down.

I'm using the latest version of NPMplus and I have Websocket-Support and SSL with "enforce HTTPS" enabled.

Any help would be appreciated :)

**Comment by Zoey2936** [comment]
see https://github.com/ZoeyVid/NPMplus/issues/1188 / https://github.com/ZoeyVid/NPMplus/discussions/1249, the issue is pinned
