### ISSUE TITLE
wrong mime-type for wav file

### ISSUE THREAD

**Issue by realies** [ZoeyVid/NPMplus#1262]
downloading a wav from a fancy-index dir is incorrectly streamed as content-type: text/plain;
can npmplus ship with a more complete mime-type list?

**Comment by Zoey2936** [comment]
I could either change the default mime type to `application/octet-stream` or you provide a patch to freenginx (currently used by NPMplus) or nginx or angie

**Comment by Zoey2936** [comment]
I think using application/octet-stream as default would be the best solution

**Comment by Zoey2936** [comment]
done: https://github.com/ZoeyVid/NPMplus/commit/631af68c25a8cca034aa1943aa1c5c3511ea8ea0 will be released soon
