### ISSUE TITLE
add option to hide server type

### ISSUE THREAD

**Issue by realies** [ZoeyVid/NPMplus#1264]
the ability to hide all server tags such as nginx or npmplus are good for privacy and security;

e.g.
```<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>NPMplus</center>
</body>
</html>
```

**Comment by Zoey2936** [comment]
Not sure, headers are already hidden, but changing what is written in the footer of error pages would require changes on the source code and leaving it empty would make it also identifiable, because it would be nearly the only proxy solution not saying its name on the error page

**Comment by realies** [comment]
it would make it ambiguous, rather than immediately identifiable

**Comment by Zoey2936** [comment]
yes, but changing the source code of the webserver for this little benefit? not worth in my eyes

**Comment by Zoey2936** [comment]
also it is not immediately identifiable, you need to trigger the error page of nginx, also you can change the error pages yourself if you want https://freenginx.org/en/docs/http/ngx_http_core_module.html#error_page (using the files in the nginx_custom folder)

**Comment by realies** [comment]
i meant immediately identifiable when having force https enabled and accessing an http address;
the code block is from a `curl http://my-npmplus-instance` call
i think it's worth having a way to anonymise the web server, especially with the ever-increasing web scraping

**Comment by Zoey2936** [comment]
there is still no advantage that would justify modifying the source code (of (free)nginx)

**Comment by realies** [comment]
why would the source code of freenginx need modifying for this?

**Comment by Zoey2936** [comment]
because it is hard coded: https://github.com/freenginx/nginx/blob/6f187a2e7c4734c81d2d226aa078131743f4ae4d/src/http/ngx_http_special_response.c#L36

**Comment by realies** [comment]
interesting, is npmplus complied with NGINX_NAME set to NPMplus?

**Comment by Zoey2936** [comment]
yes this is changed with a singel sed command: https://github.com/ZoeyVid/nginx-quic/blob/5698295c917bc42852f71606b5238ea02fb0f8f4/Dockerfile#L51
but even if I delete all lines which contains `<hr><center>` in the ngx_http_special_response.c file, just because how the error calls are named or the rest of the page is styled

**Comment by realies** [comment]
how do you feel about a PR that allows NGINX_NAME to be set to an env var?

**Comment by Zoey2936** [comment]
how do you want to do this? 
https://github.com/freenginx/nginx/blob/6f187a2e7c4734c81d2d226aa078131743f4ae4d/src/core/nginx.h#L15
it is defined as a constant

**Comment by realies** [comment]
maybe something like this, i haven't tested it
```diff

- sed -i "s|freenginx|NPMplus|g" /src/nginx/src/core/nginx.h && \

+ RUN echo 'const char* ngx_get_server_name(void) { const char* env_name = getenv("NPM_SERVER_NAME"); return env_name ? env_name : "NPMplus"; }' > /src/nginx/src/core/ngx_server_name.c && \
+     sed -i '/#define NGINX_NAME.*/{h;s/.*/const char* ngx_get_server_name(void);/p;g;s/.*/#define NGINX_NAME ngx_get_server_name()/}' /src/nginx/src/core/nginx.h && \
+     sed -i '/ngx_string.o/a ngx_server_name.o \\' /src/nginx/src/core/Makefile && \

```

**Comment by Zoey2936** [comment]
What you can do is to provide a patch to freenginx, angie and nginx which adds a config option to hide this part of the error page/change its value, but I don't think they will merge it. If they do, I will add an env which allows changing this config option.

I understand that this would be an improvement for NPNplus, but for me the advantage is too low to make changes to the source code.

Delete all lines which contains `<hr><center>` in the ngx_http_special_response.c file, would be possible from my side, but I still think that this change would make no actual improvement in security. 
So if this would be enough for you, you can open a PR on the nginx-quic repo adding a sed command to the Dockerfile, which deletes these lines. (Or the patch to freenginx/angie/nginx)

But from my side this is closed. I will not include bigger changes to the webserver source code if they don't provide a real benefit

**Comment by realies** [comment]
> but for me the advantage is too low to make changes to the source code

that's why i asked what if i open a pull request, still a no?

**Comment by Zoey2936** [comment]
I can't stop you from sending patches to freenginx/angie/nginx

**Comment by Zoey2936** [comment]
for the Dockerfile of the nginx-quic repo, only deleting the lines, not more

**Comment by realies** [comment]
i mean a patch to nginx-quic where you patch the NGINX_NAME value

**Comment by Zoey2936** [comment]
no, please provide this to freenginx/angie/nginx
