### ISSUE TITLE
Upgrading from 417 > 418+ breaks proxy host for the NPM+ web panel

### ISSUE THREAD

**Issue by DessertOverlord** [ZoeyVid/NPMplus#1277]
For a few months I hosted NPM on an RPi5, and recently I have been migrating all of my containers over to my x86 server PC. When I did so, I accidentally updated NPM+ to latest, up from v417 on Dockerhub. The only thing that appears to have broken is that previously I had a proxy host that went from https://npm.mydomain.tld/ to https://127.0.0.1:81, so that I could remotely access the webUI. 

I use Cloudflare's tunnels and SSL, and my setup was working in v417, but updating to v418 irreversibly breaks it. Navigating to https://npm.mydomain.tld/ enters an infinite redirect loop. I can also confirm that the "Force HTTPS" option is disabled. 

Even if I tear the container down and rebuild on v417, npmplus throws an error in the logs, which implies that the breaking change lives somewhere in my persistent data:

`npmplus  | nginx: [emerg] open() "/usr/local/nginx/conf/conf.d/include/tls-ciphers-no-stapling.conf" failed (2: No such file or directory) in /data/nginx/default.conf:19
npmplus  | nginx: configuration file /usr/local/nginx/conf/nginx.conf test failed
`

The only way I have gotten this to work again is by reverting to my original backup on v417.

**Comment by Zoey2936** [comment]
yes downgrading is not supported. Can you please share the config file of the host redirecting in loop?
