### ISSUE TITLE
Unauthenticated request to APPSEC

### ISSUE THREAD

**Issue by AlexanderShK** [ZoeyVid/NPMplus#1280]
Hello,
I'm trying to setup multi-server configuration with https connection between machines. Right now there two VMs (LAPI server and NPMplus+Firewall Bouncer). Everything works as intended until https is used. With https in-use AppSec stops working with error `AppSecCheck(): Unauthenticated request to APPSEC`
Sorry for bad English 😅

**Comment by Zoey2936** [comment]
what do you mean with https is used?
