### ISSUE TITLE
Error Curiosity

### ISSUE THREAD

**Issue by blaine07** [ZoeyVid/NPMplus#1311]
Recently installed NPMplus on Unraid Server; seeing a lot of this in logs and wondering if it's something I have done wrong?

`2024/12/16 17:01:35 [alert] 664#664: worker process 7993 exited with fatal code 2 and cannot be respawned
2024/12/16 17:01:35 [alert] 664#664: worker process 8015 exited with fatal code 2 and cannot be respawned
2024/12/16 17:01:35 [alert] 664#664: worker process 8016 exited with fatal code 2 and cannot be respawned
2024/12/16 17:01:35 [alert] 664#664: worker process 8038 exited with fatal code 2 and cannot be respawned
2024/12/16 17:01:35 [alert] 664#664: worker process 8039 exited with fatal code 2 and cannot be respawned
2024/12/16 17:01:35 [alert] 664#664: worker process 8057 exited with fatal code 2 and cannot be respawned
2024/12/16 17:01:35 [alert] 664#664: worker process 8061 exited with fatal code 2 and cannot be respawned
2024/12/16 17:01:35 [alert] 664#664: worker process 8072 exited with fatal code 2 and cannot be respawned
2024/12/16 17:01:35 [alert] 664#664: worker process 8085 exited with fatal code 2 and cannot be respawned
2024/12/16 17:01:35 [alert] 664#664: worker process 8086 exited with fatal code 2 and cannot be respawned
2024/12/16 17:01:35 [alert] 664#664: worker process 8094 exited with fatal code 2 and cannot be respawned
2024/12/16 17:01:35 [alert] 664#664: worker process 8103 exited with fatal code 2 and cannot be respawned
2024/12/16 17:01:35 [alert] 664#664: worker process 8107 exited with fatal code 2 and cannot be respawned
2024/12/16 17:01:35 [alert] 664#664: worker process 8118 exited with fatal code 2 and cannot be respawned
2024/12/16 17:01:35 [alert] 664#664: worker process 8126 exited with fatal code 2 and cannot be respawned
2024/12/16 18:01:35 [alert] 10758#10758: pthread_create() failed (11: Resource temporarily unavailable)
2024/12/16 18:01:35 [alert] 10787#10787: pthread_create() failed (11: Resource temporarily unavailable)
2024/12/16 18:01:35 [alert] 664#664: fork() failed while spawning "worker process" (11: Resource temporarily unavailable)
2024/12/16 18:01:35 [alert] 664#664: sendmsg() failed (9: Bad file descriptor)
2024/12/16 18:01:35 [alert] 664#664: sendmsg() failed (9: Bad file descriptor)
2024/12/16 18:01:35 [alert] 664#664: sendmsg() failed (9: Bad file descriptor)
2024/12/16 18:01:35 [alert] 664#664: sendmsg() failed (9: Bad file descriptor)
2024/12/16 18:01:35 [alert] 664#664: sendmsg() failed (9: Bad file descriptor)
2024/12/16 18:01:35 [alert] 664#664: sendmsg() failed (9: Bad file descriptor)
2024/12/16 18:01:35 [alert] 664#664: sendmsg() failed (9: Bad file descriptor)
2024/12/16 18:01:35 [alert] 664#664: sendmsg() failed (9: Bad file descriptor)
2024/12/16 18:01:35 [alert] 664#664: sendmsg() failed (9: Bad file descriptor)
2024/12/16 18:01:35 [alert] 664#664: sendmsg() failed (9: Bad file descriptor)
2024/12/16 18:01:35 [alert] 664#664: sendmsg() failed (9: Bad file descriptor)
2024/12/16 18:01:35 [alert] 664#664: sendmsg() failed (9: Bad file descriptor)
2024/12/16 18:01:35 [alert] 664#664: sendmsg() failed (9: Bad file descriptor)
2024/12/16 18:01:35 [alert] 664#664: sendmsg() failed (9: Bad file descriptor)
2024/12/16 18:01:35 [alert] 664#664: sendmsg() failed (9: Bad file descriptor)
2024/12/16 18:01:35 [alert] 664#664: sendmsg() failed (9: Bad file descriptor)
2024/12/16 18:01:35 [alert] 664#664: sendmsg() failed (9: Bad file descriptor)
2024/12/16 18:01:35 [alert] 664#664: sendmsg() failed (9: Bad file descriptor)
2024/12/16 18:01:35 [alert] 664#664: sendmsg() failed (9: Bad file descriptor)
2024/12/16 18:01:35 [alert] 664#664: sendmsg() failed (9: Bad file descriptor)
2024/12/16 18:01:35 [alert] 664#664: sendmsg() failed (9: Bad file descriptor)
2024/12/16 18:01:35 [alert] 664#664: sendmsg() failed (9: Bad file descriptor)
2024/12/16 18:01:35 [alert] 664#664: sendmsg() failed (9: Bad file descriptor)
2024/12/16 18:01:35 [alert] 664#664: sendmsg() failed (9: Bad file descriptor)
2024/12/16 18:01:35 [alert] 664#664: sendmsg() failed (9: Bad file descriptor)
2024/12/16 18:01:35 [alert] 664#664: sendmsg() failed (9: Bad file descriptor)
2024/12/16 18:01:35 [alert] 664#664: sendmsg() failed (9: Bad file descriptor)
2024/12/16 18:01:35 [alert] 664#664: sendmsg() failed (9: Bad file descriptor)
2024/12/16 18:01:35 [alert] 664#664: sendmsg() failed (9: Bad file descriptor)
2024/12/16 18:01:35 [alert] 664#664: sendmsg() failed (9: Bad file descriptor)
2024/12/16 18:01:35 [alert] 664#664: sendmsg() failed (9: Bad file descriptor)
2024/12/16 18:01:35 [alert] 664#664: sendmsg() failed (9: Bad file descriptor)
2024/12/16 18:01:35 [alert] 664#664: sendmsg() failed (9: Bad file descriptor)
2024/12/16 18:01:35 [alert] 664#664: sendmsg() failed (9: Bad file descriptor)
2024/12/16 18:01:35 [alert] 664#664: sendmsg() failed (9: Bad file descriptor)
2024/12/16 18:01:35 [alert] 664#664: sendmsg() failed (9: Bad file descriptor)
2024/12/16 18:01:35 [alert] 664#664: sendmsg() failed (9: Bad file descriptor)
2024/12/16 18:01:35 [alert] 664#664: sendmsg() failed (9: Bad file descriptor)
2024/12/16 18:01:35 [alert] 664#664: sendmsg() failed (9: Bad file descriptor)
2024/12/16 18:01:35 [alert] 664#664: sendmsg() failed (9: Bad file descriptor)
2024/12/16 18:01:35 [alert] 664#664: sendmsg() failed (9: Bad file descriptor)
2024/12/16 18:01:35 [alert] 664#664: sendmsg() failed (9: Bad file descriptor)
2024/12/16 18:01:35 [alert] 664#664: sendmsg() failed (9: Bad file descriptor)
2024/12/16 18:01:35 [alert] 664#664: sendmsg() failed (9: Bad file descriptor)
2024/12/16 18:01:35 [alert] 664#664: sendmsg() failed (9: Bad file descriptor)
2024/12/16 18:01:35 [alert] 664#664: sendmsg() failed (9: Bad file descriptor)
2024/12/16 18:01:35 [alert] 664#664: sendmsg() failed (9: Bad file descriptor)
2024/12/16 18:01:35 [alert] 664#664: sendmsg() failed (9: Bad file descriptor)
2024/12/16 18:01:35 [alert] 664#664: sendmsg() failed (9: Bad file descriptor)
2024/12/16 18:01:35 [alert] 664#664: sendmsg() failed (9: Bad file descriptor)
2024/12/16 18:01:35 [alert] 664#664: sendmsg() failed (9: Bad file descriptor)
2024/12/16 18:01:35 [alert] 664#664: sendmsg() failed (9: Bad file descriptor)
2024/12/16 18:01:35 [alert] 664#664: sendmsg() failed (9: Bad file descriptor)
2024/12/16 18:01:35 [alert] 664#664: sendmsg() failed (9: Bad file descriptor)
2024/12/16 18:01:35 [alert] 664#664: sendmsg() failed (9: Bad file descriptor)
2024/12/16 18:01:35 [alert] 664#664: sendmsg() failed (9: Bad file descriptor)
2024/12/16 18:01:35 [alert] 664#664: sendmsg() failed (9: Bad file descriptor)
2024/12/16 18:01:35 [alert] 664#664: sendmsg() failed (9: Bad file descriptor)
2024/12/16 18:01:35 [alert] 664#664: sendmsg() failed (9: Bad file descriptor)
2024/12/16 18:01:35 [alert] 664#664: sendmsg() failed (9: Bad file descriptor)
2024/12/16 18:01:35 [alert] 664#664: sendmsg() failed (9: Bad file descriptor)
2024/12/16 18:01:35 [alert] 664#664: sendmsg() failed (9: Bad file descriptor)
2024/12/16 18:01:35 [alert] 664#664: sendmsg() failed (9: Bad file descriptor)
2024/12/16 18:01:35 [alert] 664#664: worker process 10758 exited with fatal code 2 and cannot be respawned
2024/12/16 18:01:35 [alert] 664#664: worker process 10787 exited with fatal code 2 and cannot be respawned`

**Comment by blaine07** [comment]
Also saw this at Startup; maybe defining user not necessary on unraid anymore?::

`useradd warning: npm's uid 99 outside of the UID_MIN 1000 and UID_MAX 6000 range.
chown: cannot access '/proc/self/fd/3': No such file or directory
chown: cannot access '/proc/self/fd/4': No such file or directory
chown: cannot access '/proc/self/fd/5': No such file or directory
2024/12/16 18:26:18 [notice] 6112#6112: ModSecurity-nginx v1.0.3 (rules loaded inline/local/remote: 0/7/0)
2024/12/16 18:26:18 [alert] 6115#6115: sched_setaffinity() failed (22: Invalid argument)
2024/12/16 18:26:18 [alert] 6116#6116: sched_setaffinity() failed (22: Invalid argument)
2024/12/16 18:26:18 [alert] 6117#6117: sched_setaffinity() failed (22: Invalid argument)
2024/12/16 18:26:18 [alert] 6120#6120: sched_setaffinity() failed (22: Invalid argument)
removed '/data/tls/certbot/archive/npm-2/cert1.pem'
removed '/data/tls/certbot/archive/npm-2/privkey1.pem'
removed '/data/tls/certbot/archive/npm-2/chain1.pem'
removed '/data/tls/certbot/archive/npm-2/fullchain1.pem'
'/usr/local/nginx/conf/conf.d/include/coreruleset/plugins/README.md' -> '/data/etc/modsecurity/crs-plugins/README.md'
'/usr/local/nginx/conf/conf.d/include/coreruleset/plugins/empty-after.conf' -> '/data/etc/modsecurity/crs-plugins/empty-after.conf'
'/usr/local/nginx/conf/conf.d/include/coreruleset/plugins/empty-before.conf' -> '/data/etc/modsecurity/crs-plugins/empty-before.conf'
'/usr/local/nginx/conf/conf.d/include/coreruleset/plugins/empty-config.conf' -> '/data/etc/modsecurity/crs-plugins/empty-config.conf'
no DEFAULT_CERT_ID set, using dummycerts.
Working on file: /data/nginx/default.conf
Working on file: /data/nginx/proxy_host/1.conf
Success.`

**Comment by Zoey2936** [comment]
Please try with a uid within the supported range
