### ISSUE TITLE
Getting "512 worker_connections are not enough" on High Load

### ISSUE THREAD

**Issue by maieredv-manuel** [ZoeyVid/NPMplus#1314]
Hey! 

were using NPMPlus for 23 Proxy and 11 Stream Hosts.
Now we have the problem when our internal users are accessing the internal applications we are getting the "512 worker_connections are not enough" Message.

I found that there is an setting in the ngnix.conf file, but i think when ive edit this file, on the next update it will be changed to default!? Also there is an option that nginx can handle the worker_connection itselfs.

Can he have an ENV option for Settings? Or any otherway?

**Comment by Zoey2936** [comment]
>  Also there is an option that nginx can handle the worker_connection itselfs.

which exactly?

> Can he have an ENV option for Settings? Or any otherway?

if nginx can do this automatic then I would do this, if not then it depends if increasing this value has any downsides, if not then I can jsut increase the default

**Comment by maieredv-manuel** [comment]
https://www.sabatino.dev/misconfigured-nginx-worker_connections-caused-downtime/ 

I went to the nginx docs to read up about this parameter, and by default this was configured to 512.

Because of our many simultaneous websocket connections, we were effectively hitting the 512 limit, and NGINX was not configured to increase the worker_processes, so when our application server would hit this limit, it stopped accepting any new incoming requests.

I resolved this by increasing our [worker_connections](https://nginx.org/en/docs/ngx_core_module.html?ref=sabatino.dev#worker_connections) to 768 and I changed the [worker_processes](https://nginx.org/en/docs/ngx_core_module.html?ref=sabatino.dev#worker_processes) configuration from 1 to auto, so nginx would add extra workers if needed.

```
worker_processes auto;
events {
	worker_connections 768;
}
```

**Comment by Zoey2936** [comment]
the default for one of the values should already be auto:
https://github.com/ZoeyVid/NPMplus/blob/e5ecf35a89d6b18e4ab50a2199383765408672ba/rootfs/usr/local/nginx/conf/nginx.conf#L5

**Comment by maieredv-manuel** [comment]
Ah okay, thats the setting for allocating all CPU Cores - thats good.
Now we need the "worker_connections", i didnt found that setting in the nginx.conf !? that means when nothing is set in the config file, the default is set!?

**Comment by Zoey2936** [comment]
It should use the value written in nginx docs

**Comment by maieredv-manuel** [comment]
So can we change the value via "/data/nginx_custom/events.conf" or gets that file also an "reset" when updating?

**Comment by maieredv-manuel** [comment]
Ive changed the "/data/nginx_custom/events.conf" with "worker_connections 768;" and restartet the container, actually it started, but i dont know if that really changed anything ... do you know a way to check the current loaded config or get the actual worker_connections?

**Comment by Zoey2936** [comment]
`docker exec npmplus nginx -T` should output the full loaded config

**Comment by maieredv-manuel** [comment]
thats saadly only the output of all configs loaded, so only the "include /data/nginx_custom/events.conf;" is in the output, not if the process really uses the changed "worker_connections" value :-/

But okay, ill test it after the holidays, when next time all users are in the office :-) ill report again! 

Thanks for your help and merry christmas!

**Comment by Zoey2936** [comment]
Do you think increasing worker_connections by default is a bad idea?
And how many cpu cores has this system? Since worker_procces should be identical to the number of cpu threads.

Any many thanks!

**Comment by maieredv-manuel** [comment]
Puuuh, i dont know if its needed for all installations. 
When it can be done by editing that one file, its not that big deal.

My machine has only 1 CPU Core, but that wasnt the problem, cpu load is at ~5-10% at this time when ive got the "512 worker_connections are not enough" errors. 
I think auto is a good setting for "worker_processes" so nginx can scale up when its needed.

**Comment by Zoey2936** [comment]
The total connections are calculated by processes*connection, so doubling the cpu cores would double the total connections

**Comment by maieredv-manuel** [comment]
Aha, okay ... 
That makes sense - but the CPU load isnt the problem, like i said, we have around 10% Load at this time ...

But i think for the most installations with more then one CPU Core it shouldt be an problem.

**Comment by Zoey2936** [comment]
I will convert this to a discussion
