### ISSUE TITLE
IPv6 Address as Domain Name

### ISSUE THREAD

**Issue by dionperera** [ZoeyVid/NPMplus#1321]
I would like to put an IPv6 address in this box. It lets me put in domain names and IPv4 addresses without issue. However, if I try and put in an IPv6 address, even if surrounded with brackets, I get the error: data/domain_names/0 must match pattern "^[^&| @!#%^();:/\\}{=+?<>,~`'"]+$"
I would like to control what happens when the server's ipv6 address is directly accessed the same way I can with ipv4. 
![image](https://github.com/user-attachments/assets/f0ae3af8-1565-49ac-8a3b-ed31536c2963)

**Comment by Zoey2936** [comment]
Will be added, but will take some time

**Comment by Zoey2936** [comment]
will be included in the next release

**Comment by Zoey2936** [comment]
if you want, you can test this alpha/prerelease: https://github.com/ZoeyVid/NPMplus/releases/tag/2025-01-03-alpha (but make a backup first)
