### ISSUE TITLE
nginx: [emerg] "quic_bpf" directive is not allowed here in /usr/local/nginx/conf/nginx.conf

### ISSUE THREAD

**Issue by rokoman** [ZoeyVid/NPMplus#1323]
The quic_bpf directive must be placed in the main (global) context of nginx configuration. It cannot be inside http, events, or server blocks as it's a global setting that needs to be initialized before nginx workers are spawned.

https://nginx.org/en/docs/http/ngx_http_v3_module.html#quic_bpf

**Comment by Zoey2936** [comment]
Thanks, I will move it
