### ISSUE TITLE
High Frequency Requests to `/api/reports/hosts` Endpoint Cause UI Issues in Fresh Install

### ISSUE THREAD

**Issue by DenixJG** [ZoeyVid/NPMplus#1326]
### Issue Description  
After a fresh installation of the latest version the Frontend makes an unusually high number of requests to the API endpoint `/api/reports/hosts`.  

#### Problem:  
- Over 220 requests are sent to this endpoint within approximately 5 seconds.  
- This causes UI links to refresh constantly, making them unusable, as the components are being repainted every few milliseconds.  

![image](https://github.com/user-attachments/assets/c631dda8-e58c-43e7-baf0-1ff47e5b14e0)

#### Steps to Reproduce:  
1. Install the latest version of the application.  
2. Navigate to `https://localhost:81/` that interacts with `/api/reports/hosts`.  

#### Environment:  
- **Version:** `2.12.1+b091ad0`  
- **Browser:** Chrome and Firefox 
- **OS:** Ubuntu 24.04 and Docker

#### Additional Information:  
No special config made in the container

**Comment by Zoey2936** [comment]
yes this issue is known and fixed in develop, but develop is currently broken, so please don't use it currently. The issue also exists in the latest upstream release

**Comment by Zoey2936** [comment]
The fix will be included in the next release

**Comment by Zoey2936** [comment]
if you want, you can test this alpha/prerelease: https://github.com/ZoeyVid/NPMplus/releases/tag/2025-01-03-alpha (but make a backup first)

**Comment by DenixJG** [comment]
Thank you very much! I'll try to test it again as soon as I can.
