### ISSUE TITLE
no module named 'zope'

### ISSUE THREAD

**Issue by rastyu** [ZoeyVid/NPMplus#234]
**Checklist**
- Have you pulled and found the error with `zoeyvid/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - No
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**

![npm](https://user-images.githubusercontent.com/48859414/229573220-2ebbe0c8-69fc-4239-bc91-55d150fe2878.jpeg)

**Nginx Proxy Manager Version**

  - zoeyvid/nginx-proxy-manager:latest

**Comment by Zoey2936** [comment]
which dns provider did you used?

**Comment by rastyu** [comment]
I am using DNSPOD provider apply for a Wildcard Certificate.

**Comment by Zoey2936** [comment]
I've added zope to the pip install command, can you please try using the :develop tag, please?

**Comment by rastyu** [comment]
thanks,it works. 
![1](https://user-images.githubusercontent.com/48859414/229804891-b6c8ce22-17a5-401d-a328-4fa939d9413f.jpeg)

**Comment by Zoey2936** [comment]
I will push it now to latest

**Comment by Zoey2936** [comment]
Hi @rastyu, I've changed to an updated dnspod certbot plugin (https://github.com/ZoeyVid/nginx-proxy-manager/commit/66b6cca78e3dfc4503521db220d95d8c8ffc42a2) and removed zope again, could you please try the develop tag again and reports if the new plugin works?

**Comment by rastyu** [comment]
the new develop docker image works fine
![网页捕获_6-4-2023_23633_192 168 10 20](https://user-images.githubusercontent.com/48859414/230421592-6ffc5779-5220-4777-9cac-a44705e62332.jpeg)

**Comment by Zoey2936** [comment]
Thanks! I will push it now to latest

**Comment by Feriman22** [comment]
Hi @Zoey2936,

I have the very similar issue in the latest version (2.12.3+0a85402) with FreeDNS or even with Dynu providers.

I tried to install the missing zope inside the container with `pip install zope` command, but no success (installation failed).

**Comment by Zoey2936** [comment]
please report this to the dns plugin, zope was removed out of certbot which makes such old plugins incompatible
