### ISSUE TITLE
502 on reload [Error when proxying nginx-proxy-manager to itself]

### ISSUE THREAD

**Issue by dontcrash** [ZoeyVid/NPMplus#241]
This bug doesn't happen with the original branch.

If I first navigate to nginx.domain.com and then only navigate with my cursor, it's fine:

nginx.domain.com - fine
nginx.domain.com/nginx/proxy - fine

If I however try to enter nginx.domain.com/nginx/proxy in the URL bar or refresh the page with anything other than nginx.domain.com, I get a 502 bad gateway:

upstream prematurely closed connection while reading response header from upstream, client: RFC1918_ADDRESS, server: nginx.domain.com, request: "GET /nginx/proxy HTTP/2.0", upstream: "https://127.0.0.1:81/nginx/proxy", host: "nginx.domain.com", referrer: "https://nginx.domain.com/nginx/proxy"

**Comment by dontcrash** [comment]
First request, loads fine:

Request URL: https://nginx.domain.com/
Request Method: GET
Status Code: 304 
Remote Address: RFC1918_ADDRESS:443
Referrer Policy: strict-origin-when-cross-origin
alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
date: Sat, 15 Apr 2023 09:48:07 GMT
etag: "6431df19-677"
last-modified: Sat, 08 Apr 2023 21:39:37 GMT
server: nginx-proxy-manager/1.23.4 (nginx-quic)
strict-transport-security: max-age=63072000; includeSubDomains; preload
vary: Accept-Encoding
:authority: nginx.domain.com
:method: GET
:path: /
:scheme: https
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
accept-encoding: gzip, deflate, br
accept-language: en-GB,en-US;q=0.9,en;q=0.8
cache-control: max-age=0
if-modified-since: Sat, 08 Apr 2023 21:39:37 GMT
if-none-match: W/"6431df19-677"
sec-ch-ua: "Not:A-Brand";v="99", "Chromium";v="112"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
sec-fetch-dest: document
sec-fetch-mode: navigate
sec-fetch-site: none
sec-fetch-user: ?1
upgrade-insecure-requests: 1
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36


After clicking Proxy Hosts:

Request URL: https://nginx.domain.com/api/nginx/proxy-hosts?expand=owner,access_list,certificate
Request Method: GET
Status Code: 200 
Remote Address: RFC1918_ADDRESS:443
Referrer Policy: strict-origin-when-cross-origin
alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
cache-control: no-cache, no-store, max-age=0, must-revalidate
content-encoding: br
content-type: application/json; charset=utf-8
date: Sat, 15 Apr 2023 09:51:31 GMT
etag: W/"2ac8-bqiDYpWdIik7v6ROO+rP+E8si3U"
expires: 0
pragma: no-cache
referrer-policy: strict-origin-when-cross-origin
server: nginx-proxy-manager/1.23.4 (nginx-quic)
strict-transport-security: max-age=63072000; includeSubDomains; preload
vary: Accept-Encoding
vary: Accept-Encoding
vary: Accept-Encoding
x-content-type-options: nosniff
x-frame-options: DENY
x-xss-protection: 1; mode=block
:authority: nginx.vlan.au
:method: GET
:path: /api/nginx/proxy-hosts?expand=owner,access_list,certificate
:scheme: https
accept: application/json, text/javascript, */*; q=0.01
accept-encoding: gzip, deflate, br
accept-language: en-GB,en-US;q=0.9,en;q=0.8
authorization: Bearer REDACTED_TOKEN
content-type: application/json; charset=UTF-8
referer: https://nginx.domain.com/nginx/proxy
sec-ch-ua: "Not:A-Brand";v="99", "Chromium";v="112"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: same-origin
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36


F5 refresh page:

Request URL: https://nginx.domain.com/nginx/proxy
Request Method: GET
Status Code: 502 
Remote Address: RFC1918_ADDRESS:443
Referrer Policy: strict-origin-when-cross-origin
content-length: 586
content-type: text/html
date: Sat, 15 Apr 2023 09:48:20 GMT
referrer-policy: strict-origin-when-cross-origin
server: nginx-proxy-manager/1.23.4 (nginx-quic)
strict-transport-security: max-age=63072000; includeSubDomains; preload
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
:authority: nginx.domain.com
:method: GET
:path: /nginx/proxy
:scheme: https
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
accept-encoding: gzip, deflate, br
accept-language: en-GB,en-US;q=0.9,en;q=0.8
cache-control: max-age=0
sec-ch-ua: "Not:A-Brand";v="99", "Chromium";v="112"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
sec-fetch-dest: document
sec-fetch-mode: navigate
sec-fetch-site: none
sec-fetch-user: ?1
upgrade-insecure-requests: 1
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36


Seems that the HTTP request missing the path header and the actual request URL is different.

**Comment by Zoey2936** [comment]
you mean opening /nginx/proxy unauthorized? yes can confirm that will return 502, but authorized it works

**Comment by dontcrash** [comment]
Yeah I can see what is going on here without the bearer it fails, tested from curl, wondering if that token should be stored as a cookie and passed to the web server, maybe not really an issue - apologies

**Comment by Zoey2936** [comment]
I'm not sure which patch this caused, I will try to fix it, but with a low priority, since it works. maybe it was a dependencie update?

**Comment by dontcrash** [comment]
Ended up working around this by adding the following to custom conf:

```
location /nginx/proxy {
    if ($http_authorization ~ "") {
        return 301 "https://nginx.domain.com";
    }
}
```

**Comment by Zoey2936** [comment]
Since you found a workaround for you, I don't want to downgrade deps and I think it is not a big bug/security problem, I would like to close this Issue, is this okay for you?

**Comment by dontcrash** [comment]
Sure
