### ISSUE TITLE
Internal server error/domain already in use

### ISSUE THREAD

**Issue by dontcrash** [ZoeyVid/NPMplus#283]
2.10.3+cabf78f
When editing it creating a new proxy host, it tells me there has been an internal server error.

```
[Nginx    ] › ⬤  debug     Deleting file: /data/nginx/proxy_host/2.conf
[Nginx    ] › ℹ  info      Restarting Nginx
[Nginx    ] › ⬤  debug     Deleting file: /data/nginx/proxy_host/2.conf
[Nginx    ] › ℹ  info      Restarting Nginx
[Nginx    ] › ⬤  debug     Deleting file: /data/nginx/proxy_host/2.conf
```

**Comment by Zoey2936** [comment]
That's not a bug, this behavior is wanted, since otherwise modsec will cause a memory leak.

**Comment by dontcrash** [comment]
Not quite sure I understand what’s going on here, so the latest tag version has made it so users are unable to modify or add a new host?

**Comment by Zoey2936** [comment]
No the changes are done, but because of the connection los (nginx gets killed and relaunched) the frontend reports an error

**Comment by Zoey2936** [comment]
you can check the file in your root file system, it is changed, I know not a good solution, but the memory leak of modsec basically made my server freez while reloading nginx

**Comment by Zoey2936** [comment]
See here: https://github.com/SpiderLabs/ModSecurity/issues/2848#issuecomment-1570732794

**Comment by Zoey2936** [comment]
@dontcrash can you confirm that it gets changed on disk?

**Comment by dontcrash** [comment]
> @dontcrash can you confirm that it gets changed on disk?

Yes files are changed, not really an ideal solution though :/

**Comment by Zoey2936** [comment]
#296 seems to be caused by the same

**Comment by afzl-wtu** [comment]
same issue here

**Comment by Zoey2936** [comment]
@dontcrash does this issue still persist for you? Since for me, it vanished, after switching from kill to nginx own stop command.

**Comment by Zoey2936** [comment]
Will close, since I can't confirm this anymore
