### ISSUE TITLE
80 failed (13: Permission denied)

### ISSUE THREAD

**Issue by Joly0** [ZoeyVid/NPMplus#290]
**Checklist**
- Have you pulled and found the error with `zoeyvid/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**

Trying to start the container using this command `docker run -d --name nginx-proxy-manager --restart unless-stopped --network host -v /config/Nginx-Proxy-Manager:/data -e TZ=Europe/Berlin -e PUID=1000 -e PGID=1000 zoeyvid/nginx-proxy-manager:latest`
displays these errors in the docker logs 
![grafik](https://github.com/ZoeyVid/nginx-proxy-manager/assets/13993216/e7db6021-fcc2-4a03-ace6-6db7a191752a)
and i cant reach the webui or anything afterwards.
Running docker container ls shows the container in status "starting" for a while, until it switches to "unhealthy"

**Nginx Proxy Manager Version**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Operating System**

**Additional context**

**Comment by Zoey2936** [comment]
can you please try the develop channel? (currently there is nothing breaking in it)

**Comment by Joly0** [comment]
Using develop and the command above i get this:
![grafik](https://github.com/ZoeyVid/nginx-proxy-manager/assets/13993216/803130e0-4799-4d2f-b3e8-83ec7c41c6f9)

**Comment by Zoey2936** [comment]
do you have something running on port 80? (the warning can be ignored)

**Comment by Joly0** [comment]
Nope

**Comment by Zoey2936** [comment]
can you please stop the npm and run: `netstat -tulpn | grep :80`

**Comment by Joly0** [comment]
Did that, no output

**Comment by Joly0** [comment]
![grafik](https://github.com/ZoeyVid/nginx-proxy-manager/assets/13993216/4ef25b9b-abbf-4ff8-a039-66b765aa7333)

**Comment by Zoey2936** [comment]
ahh i see the problem, you used non root, please add `net.ipv4.ip_unprivileged_port_start=0` at the end of `/etc/sysctl.conf` and restart your system (this is also written inside the readme).

**Comment by Joly0** [comment]
yep, that fixed it

**Comment by Zoey2936** [comment]
But please keep in mind, now every non-root user on your server can now bind ports lower than 1024

**Comment by afzl-wtu** [comment]
> ahh i see the problem, you used non root, please add `net.ipv4.ip_unprivileged_port_start=0` at the end of `/etc/sysctl.conf` and restart your system (this is also written inside the readme).

Thanks. I also needed it.

**Comment by NolandTech** [comment]
> ahh i see the problem, you used non root, please add `net.ipv4.ip_unprivileged_port_start=0` at the end of `/etc/sysctl.conf` and restart your system (this is also written inside the readme).

"(this is also written inside the readme)" The Main Readme.md on the repositoy? No it's not.. it actually says, "Quick Setup
Install Docker and Docker Compose (podman or docker rootless may also work)"

**Comment by Zoey2936** [comment]
yes, sorry, I removed it 3 months ago: https://github.com/ZoeyVid/NPMplus/commit/423ec0136d75429a0a54fa34a87277de73a6a53d#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5 will readd it
