### ISSUE TITLE
 Domain is already in use

### ISSUE THREAD

**Issue by rokoman** [ZoeyVid/NPMplus#296]
When run docker compose and add proxy host i found domain is already in use

**Comment by Zoey2936** [comment]
does the domain maybe already exist as redirect host, which is disabled?

**Comment by rokoman** [comment]
> does the domain maybe already exist as redirect host, which is disabled?

No, i tested new sub domain.

I create new droplet in vps
and install docker  and add new domain for testing

I found 2 problem
- xxxx (domain) is already in use. but system add to db.
- when i delete error found Internal error.

this docker compose me

> version: "3"
services:
  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: zoeyvid/nginx-proxy-manager
    restart: always
    network_mode: host
    volumes:
      - "./data:/data"
    environment:
      - "TZ=Asia/Bangkok"
      - "PUID=1000"    # add sysctl success
      - "PGID=1000"

you can test this https://45.32.117.41:81/
user : admin@exampletest.com
pass : iArhP1j7p1P6TA92FA2FMbbUGYqwcYzxC4AVEe12Wbi94FY9gNN62aKyF1shrvG4NycjjX9KfmDQiwkLZH1ZDR9xMjiG2QmoHXi

**Comment by Zoey2936** [comment]
so this happens with every domain?

**Comment by rokoman** [comment]
> so this happens with every domain?

yes

**Comment by Zoey2936** [comment]
> > does the domain maybe already exist as redirect host, which is disabled?
> 
> No, i tested new sub domain.
> 
> I create new droplet in vps and install docker and add new domain for testing
> 
> I found 2 problem
> 
>     * xxxx (domain) is already in use. but system add to db.
> 
>     * when i delete error found Internal error.
> 
> 
> this docker compose me
> 
> > version: "3"
> > services:
> > nginx-proxy-manager:
> > container_name: nginx-proxy-manager
> > image: zoeyvid/nginx-proxy-manager
> > restart: always
> > network_mode: host
> > volumes:
> > - "./data:/data"
> > environment:
> > - "TZ=Asia/Bangkok"
> > - "PUID=1000"    # add sysctl success
> > - "PGID=1000"
> 
> you can test this https://45.32.117.41:81/ user : [admin@exampletest.com](mailto:admin@exampletest.com) pass : iArhP1j7p1P6TA92FA2FMbbUGYqwcYzxC4AVEe12Wbi94FY9gNN62aKyF1shrvG4NycjjX9KfmDQiwkLZH1ZDR9xMjiG2QmoHXi

I think that this is related to #283. Since the changes on your instance are apllied, even if this error shows up
