### ISSUE TITLE
Use HTTP instead of HTTPS for Admin UI

### ISSUE THREAD

**Issue by afzl-wtu** [ZoeyVid/NPMplus#338]
Is it possible to access port 81 with http request like http://127.0.0.1:81 instead of https://127.0.0.1:81. I do not want unneeded overhead on cpu. As it is my localhost.- SO why communicate in secure protocols

**Comment by Zoey2936** [comment]
it is not possible, https is required, I don't see a reason why it should be unencrypted

**Comment by afzl-wtu** [comment]
> it is not possible, https is required, I don't see a reason why it should be unencrypted

Because it is overhead on cpu why to encrypt http inside localhost?

**Comment by Zoey2936** [comment]
in a localhost scenario yes, but many people have it running in the public internet

**Comment by afzl-wtu** [comment]
Exactly. You are right. SSL is good in public but not in intercommunication of localhost. JC21 Allow to work on HTTP.

**Comment by Zoey2936** [comment]
in internal communication I don't see any downsides of encryption and externally it should be the default

**Comment by Zoey2936** [comment]
what is the problem of encryption? it maybe uses some cpu, but it is not like that few requests will kill servet

**Comment by Zoey2936** [comment]
sorry, but I will close this, even if adding an option for it would be simple, I don't want to offer the option to make the admin ui insecure
