### ISSUE TITLE
Why need to set Custom Headers?

### ISSUE THREAD

**Issue by afzl-wtu** [ZoeyVid/NPMplus#339]
This Proxy does not forward real ip of the client to listening service. I need manually set custom location these headers:
```
   proxy_set_header X-Forwarded-Host $host:$server_port;
   proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
   proxy_set_header X-Forwarded-Proto $scheme;
```
But on orignal Nginx Proxy Manager we do not need to set headers instead it automatically forward the real ip in request to listening interface.

**Comment by Zoey2936** [comment]
https://github.com/ZoeyVid/nginx-proxy-manager/blob/develop/rootfs/usr/local/nginx/conf/conf.d/include/proxy.conf they are set
