### ISSUE TITLE
Failed to Login

### ISSUE THREAD

**Issue by afzl-wtu** [ZoeyVid/NPMplus#346]
After some time docker running I can no more log in to my NGINXPROXYMANAGER:
I have to manaually docker restart nginxproxymanager.
Here are server logs:
```
2023/07/26 17:55:42 [error] 11102#11102: *332 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: _, request: "POST /api/tokens HTTP/1.1", upstream: "http://127.0.0.1:48693/tokens", host: "proxy.afzal.website", referrer: "https://proxy.afzal.website/login"
2023/07/26 17:56:07 [error] 11069#11069: *334 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: _, request: "GET /api/ HTTP/2.0", upstream: "http://127.0.0.1:48693/", host: "localhost:81"
2023/07/26 17:56:08 [error] 11135#11135: *351 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: _, request: "GET /api/ HTTP/1.1", upstream: "http://127.0.0.1:48693/", host: "proxy.afzal.website", referrer: "https://proxy.afzal.website/"
2023/07/26 17:56:23 [error] 11135#11135: *366 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: _, request: "POST /api/tokens HTTP/1.1", upstream: "http://127.0.0.1:48693/tokens", host: "proxy.afzal.website", referrer: "https://proxy.afzal.website/login"
2023/07/26 17:56:37 [error] 11069#11069: *368 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: _, request: "GET /api/ HTTP/2.0", upstream: "http://127.0.0.1:48693/", host: "localhost:81"
```

**Comment by afzl-wtu** [comment]
This issue was never faced in non php docker version.

**Comment by Zoey2936** [comment]
can you provide browser logs?

**Comment by afzl-wtu** [comment]
It says :
![image](https://github.com/ZoeyVid/nginx-proxy-manager/assets/64379149/307cbd5e-1631-422a-8b7c-92e33001e680)

**Comment by afzl-wtu** [comment]
> can you provide browser logs?

ANd there is no thing inside console of browser. It just shows bad gateway on screen

**Comment by Zoey2936** [comment]
does this occured multiple times or just onces?

**Comment by afzl-wtu** [comment]
it occurs after 5 hours at average

**Comment by Zoey2936** [comment]
can you send me the full docker logs?

**Comment by afzl-wtu** [comment]
I have just restarted docker now. Now everythng is working for sometime. Here is full log:
[nginxfulllogs.log](https://github.com/ZoeyVid/nginx-proxy-manager/files/12173924/nginxfulllogs.log)

**Comment by Zoey2936** [comment]
does the issue still exist?

**Comment by afzl-wtu** [comment]
> does the issue still exist?

I had migrated to Caddy. It is simple easy and awesome. Anyway I moved to caddy because of issue in NPM. So it is straight forward , issue is still present in NPM.

**Comment by Zoey2936** [comment]
Sorry, but I can't reproduce this error
Maybe this is something that could interest you, I plan to create based on this fork of the NPM a Caddy-Proxy-Manager

**Comment by afzl-wtu** [comment]
> Sorry, but I can't reproduce this error Maybe this is something that could interest you, I plan to create based on this fork of the NPM a Caddy-Proxy-Manager

Sorry for late reply.
There is alreaady [CaddyProxyManger](https://github.com/Pacerino/CaddyProxyManager) but kind of Dead Project.

**Comment by afzl-wtu** [comment]
> Sorry, but I can't reproduce this error Maybe this is something that could interest you, I plan to create based on this fork of the NPM a Caddy-Proxy-Manager

Caddy has a simple CaddyFile for everything but a web ui will be much more appreciate. Yes I am waiting for it.

**Comment by afzl-wtu** [comment]
The link here does not work anymore.
![image](https://github.com/ZoeyVid/nginx-proxy-manager/assets/64379149/b28e8187-ccc0-4be2-a4c9-05ed7b0035e4)

**Comment by Zoey2936** [comment]
> The link here does not work anymore. ![image](https://user-images.githubusercontent.com/64379149/258654607-b28e8187-ccc0-4be2-a4c9-05ed7b0035e4.png)

thanks! fixed now

**Comment by Zoey2936** [comment]
> > Sorry, but I can't reproduce this error Maybe this is something that could interest you, I plan to create based on this fork of the NPM a Caddy-Proxy-Manager
> 
> Sorry for late reply. There is alreaady [CaddyProxyManger](https://github.com/Pacerino/CaddyProxyManager) but kind of Dead Project.

doesn't look very useable

**Comment by Zoey2936** [comment]
> > Sorry, but I can't reproduce this error Maybe this is something that could interest you, I plan to create based on this fork of the NPM a Caddy-Proxy-Manager
> 
> Sorry for late reply. There is alreaady [CaddyProxyManger](https://github.com/Pacerino/CaddyProxyManager) but kind of Dead Project.

didn't know there is already something like that, but yes doesn't seem to be maintained

**Comment by Zoey2936** [comment]
I think I know the reason, will be fixed in the enxt release

**Comment by Zoey2936** [comment]
should be fixed now
