### ISSUE TITLE
Add custom certificate found upload failed: Internal Error

### ISSUE THREAD

**Issue by rokoman** [ZoeyVid/NPMplus#407]
![g1](https://github.com/ZoeyVid/nginx-proxy-manager/assets/1106739/a85305f4-7a38-44ae-83a3-2ec657315a79)

I found problem when upload certificate

**Error:** docker log 
[Express  ] › ⚠  warning   Cannot read properties of undefined (reading 'then')

**Comment by Zoey2936** [comment]
can you please try the :develop tag?

**Comment by rokoman** [comment]
> can you please try the :develop tag?

I tested latest image.

image: zoeyvid/nginx-proxy-manager

**Comment by Zoey2936** [comment]
please test again with this image: zoeyvid/nginx-proxy-manager:develop

**Comment by rokoman** [comment]
> please test again with this image: zoeyvid/nginx-proxy-manager:develop

same problem, i tested develop, 337-339, latest.
and other server testing original nginx proxy manager, certificate no problem.

**Comment by rokoman** [comment]
i back tested to tag 322, 323 . i found problem start on tag 323 , tag 322 no problem.

**Comment by Zoey2936** [comment]
I found the problem, will be fixed quickly

**Comment by rokoman** [comment]
I tested develop branch, can  add certificate success.
