### ISSUE TITLE
Can not used php when run PUID & GUID other user root

### ISSUE THREAD

**Issue by rokoman** [ZoeyVid/NPMplus#412]
![e3](https://github.com/ZoeyVid/nginx-proxy-manager/assets/1106739/15996206-34ec-4dcb-a0fd-d6ddd99ea451)

![e2](https://github.com/ZoeyVid/nginx-proxy-manager/assets/1106739/b7ddcd0d-53c3-437c-a9c5-274411cb11ff)

Other on README.md:
You forgot to include ; after 404

**Comment by Zoey2936** [comment]
please retry in the develop tag

**Comment by rokoman** [comment]
I found other error.

![Screenshot from 2023-09-26 14-36-01](https://github.com/ZoeyVid/nginx-proxy-manager/assets/1106739/ac468bf8-deca-4a93-a7db-a0abb70c4a1e)

**Comment by Zoey2936** [comment]
please retry

**Comment by rokoman** [comment]
I tested and it can be used. no error.
