### ISSUE TITLE
Refresh pages show This site can’t be reached

### ISSUE THREAD

**Issue by rokoman** [ZoeyVid/NPMplus#413]
![Screenshot from 2023-09-26 18-29-26](https://github.com/ZoeyVid/nginx-proxy-manager/assets/1106739/d79677f3-fd26-4b45-b5c3-4921126a5597)

When refresh (F5) all page show error, This site can’t be reached.
upstream nginx proxy manager not problem.

docker logs:
2023/09/26 13:33:32 [alert] 5267#5267: worker process 7577 exited on signal 11 (core dumped)
2023/09/26 13:34:49 [alert] 5267#5267: worker process 7610 exited on signal 11 (core dumped)
2023/09/26 13:34:49 [alert] 5267#5267: worker process 7643 exited on signal 11 (core dumped)
2023/09/26 13:34:50 [alert] 5267#5267: worker process 7855 exited on signal 11 (core dumped)

**Comment by Zoey2936** [comment]
See https://github.com/ZoeyVid/nginx-proxy-manager/issues/241
