### ISSUE TITLE
I want to disable modsecurity specific rule. or change the rule

### ISSUE THREAD

**Issue by dalso0418** [ZoeyVid/NPMplus#474]
Hello. Hello from Korea.
First, thank you for the fantastic project.

No other than using modsecurity to constantly block certain rules during host configuration.

I want to change the rule so that I can pass only the rule, is there a guide for exceptions?

![image](https://github.com/ZoeyVid/NPMplus/assets/107911055/e9540a0b-23fb-4037-ac16-9e0cd6d82bc0)

I went to the location in the error log and changed the rule to pass and applied nginx -s reload, but it is not reflected.

*This content was written through a translator, so please understand even if there are mistranslations.

**Comment by dalso0418** [comment]
npmplus    | 2023/11/07 11:22:54 [error] 1245#1245: *135 Request body limit is marked to reject the request, client: x, server: x, request: "POST /api/asset/upload HTTP/2.0", host: "x"

There are many errors like the above😢

**Comment by Zoey2936** [comment]
I will add an option for this later

**Comment by dalso0418** [comment]
Thank you for your consideration.
It's the project I was looking for!

**Comment by Zoey2936** [comment]
For your errors:
The screenshot:
- blocked by CRS, either disabled it or look if you can change something in the /opt/npm/etc/modsecurity/crs-setup.conf file

The second error log:
- I think created by default ModSecurity, I can add an config file, so you can edit the default ModSec rules

**Comment by Zoey2936** [comment]
will be added in the next release
