### ISSUE TITLE
I'd like to inform you about some bugs.

### ISSUE THREAD

**Issue by dalso0418** [ZoeyVid/NPMplus#475]
Hello! I'm saying hello again.

I would like to inquire about some bugs.

If you reload from the address below, you will get an error as shown below.
https://ip:81/nginx/proxy 

![image](https://github.com/ZoeyVid/NPMplus/assets/107911055/dcd720e3-4587-4257-a1e8-90b2b8d11d16)

npmplus    | 2023/11/07 23:24:31 [alert] 1047#1047: worker process 1399 exited on signal 11 (core dumped)
npmplus    | 2023/11/07 23:24:32 [alert] 1047#1047: worker process 1333 exited on signal 11 (core dumped)

Also, when I request a default certificate, I get an error as shown below.
![image](https://github.com/ZoeyVid/NPMplus/assets/107911055/603236de-1ba5-4e67-a7fd-6e6f027c467c)

![image](https://github.com/ZoeyVid/NPMplus/assets/107911055/e9a321ae-8526-49d9-bf54-2176a013ad98)

**log**
npmplus    | [SSL      ] › ℹ  info      Command: certbot --logs-dir /tmp/certbot-log --work-dir /tmp/certbot-work --config-dir /data/tls/certbot certonly --config "/data/tls/certbot/config.ini" --cert-name "npm-8" --authenticator webroot --preferred-challenges "dns,http" --domains "test.rocket94.com" --email "admin-sv@svrforum.com"
npmplus    | [Express  ] › ⚠  warning   Command failed: certbot --logs-dir /tmp/certbot-log --work-dir /tmp/certbot-work --config-dir /data/tls/certbot certonly --config "/data/tls/certbot/config.ini" --cert-name "npm-8" --authenticator webroot --preferred-challenges "dns,http" --domains "test.rocket94.com" --email "admin-sv@svrforum.com"
npmplus    | Saving debug log to /tmp/certbot-log/letsencrypt.log
npmplus    | Some challenges have failed.

Host is still added in this state.
![image](https://github.com/ZoeyVid/NPMplus/assets/107911055/842e75ef-86f5-45d5-b859-2302253014d4)

Please check. Thank you.

**Comment by dalso0418** [comment]
https://www.reddit.com/r/selfhosted/ People will be very interested when introduced to!

**Comment by dalso0418** [comment]
After turning on crowdsec, it seems to be fine...?? 😢

**Comment by dalso0418** [comment]
In crowdsec, the following error logs are repeated.

crowdsec    | time="07-11-2023 23:57:54" level=error msg="while fetching bouncer info: select bouncer: ent: bouncer not found: unable to query" ip=172.17.0.1
crowdsec    | time="07-11-2023 23:57:54" level=info msg="172.17.0.1 - [Tue, 07 Nov 2023 23:57:54 KST] \"GET /v1/decisions/stream?startup=true HTTP/1.1 403 300.7µs \"crowdsec-nginx-bouncer/v1.0.4\" \""


**npm plus log**
npmplus    |    /usr/local/nginx/lib/lua/crowdsec.lua:257: in function </usr/local/nginx/lib/lua/crowdsec.lua:184>, context: ngx.timer, client: 192.168.1.144, server: 0.0.0.0:81
npmplus    | 2023/11/07 23:58:34 [error] 2554#2554: *327 lua entry thread aborted: runtime error: /usr/local/nginx/lib/lua/crowdsec.lua:257: HTTP error while request to Local API '403' with message ({"message":"access forbidden"})
npmplus    | stack traceback:
npmplus    | coroutine 0:
npmplus    |    [C]: in function 'error'
npmplus    |    /usr/local/nginx/lib/lua/crowdsec.lua:257: in function </usr/local/nginx/lib/lua/crowdsec.lua:184>, context: ngx.timer, client: 192.168.1.144, server: 0.0.0.0:81

**Comment by Zoey2936** [comment]
> https://ip:81/nginx/proxy

see https://github.com/ZoeyVid/NPMplus/issues/241

> for the certbot error

please run `docker exec npmplus cat /tmp/certbot-log/letsencrypt.log` and send the output (after the error has occured)

> crowdsec

it seems like you didn't create a secret for npmplus, please check if you followed the guide in the readme

> https://www.reddit.com/r/selfhosted

I don't like to advertise my projects, if you want you can do it

**Comment by dalso0418** [comment]
It was my fault. An error occurred because the prompt was copied to the crowdsec api.

What's unique is that when Crowdsec is enabled, none of the nginx502 issues or certificate issuance issues above occur.

------------
If you disable it and successfully issue a certificate, you will get 400 errors.
![image](https://github.com/ZoeyVid/NPMplus/assets/107911055/73602ecb-cb99-4872-b8d0-76694a0bc6ab)

**Comment by Zoey2936** [comment]
what do  you mean?

**Comment by dalso0418** [comment]
Changing the Crowdsec setting from false to true addresses all other issues, including #241.

**Comment by Zoey2936** [comment]
so whcih of the many issues you listed here still exist?

**Comment by dalso0418** [comment]
There are no issues left after the Crowdsecure setting.

Thank you :)
