### ISSUE TITLE
Stream entry Offline ?

### ISSUE THREAD

**Issue by sangju41** [ZoeyVid/NPMplus#476]
Hi,

Just installed the latest version and http, https reverse proxy entries are working fine.

Stream entry status is "offline" even though, forwarding host is online. 
Same setting used to work well with regular ngnix proxy manager.

Is there anything needed more to check on npm plus ?

Thanks in advance..

**Comment by Zoey2936** [comment]
I will have a lock at this later

**Comment by Zoey2936** [comment]
fixed in the develop, will be released later

**Comment by sangju41** [comment]
> fixed in the develop, will be released later

Thank you very much for such a quick action.
