### ISSUE TITLE
Inquiries about the http/3 and crowdsec rule

### ISSUE THREAD

**Issue by dalso0418** [ZoeyVid/NPMplus#477]
Hello. You're asking a lot of questions!

It's because the project is so good, so please understand.

I have a few more questions.

I currently opened all 443 ports with TCP/UDP, but http3check.When checked on the net, it seems that communication is not possible through http3. http 1.1

![image](https://github.com/ZoeyVid/NPMplus/assets/107911055/c10b3b18-fe1b-4386-94bf-bec2a78e4cfc)
![image](https://github.com/ZoeyVid/NPMplus/assets/107911055/c77c2861-bbc6-4694-b48e-00eb603fc918)

I have another question about Crowdsec.
Currently, I can only see the list as below in the basic drawsec rule, but I would like to ask if there is a way to test if things detected in nginx are blocked.

cscli collections list

![image](https://github.com/ZoeyVid/NPMplus/assets/107911055/eb831339-8053-4549-82ea-ad3d6de2d3a7)

Thank you.
*This content was written through a translator, so please understand even if there are mistranslations.

**Comment by Zoey2936** [comment]
https://http3check.net/?host=zoeyvid.de returns HTTP/3 for me, so did you exposed udp  in all firewalls?

For crowdsec testing:
docker exec crowdsec cscli decisions add --ip 1.2.3.4 --duration 1m
Use your ip and open the site

**Comment by dalso0418** [comment]
Thank you for your reply.
but, I am using an unifi router and tcp/udp is open on both 80/443.

![image](https://github.com/ZoeyVid/NPMplus/assets/107911055/efacf1a5-5d81-4862-8f04-3990b8014cd2)

**Comment by Zoey2936** [comment]
Did crowdsec at least worked?
