### ISSUE TITLE
Nginx seem stuck at the fresh install

### ISSUE THREAD

**Issue by Railline** [ZoeyVid/NPMplus#483]
Hi, i got a little problem with NPM-Plus i want to change my old docker image form baudneo to this one more update, but on fresh install before i do any configuration i can't access to the admin interface or any port (i don't have firewall)

when i go to my log i see that
![image](https://github.com/ZoeyVid/NPMplus/assets/57727650/6c2d7b17-b746-455a-912c-23d4807bb0c7)
(i have wait more that 3 second)

I use it on unraid 6.12.4
i have try bridge and host
i have change the IPv4 Binding and NPM Ipv4 binding ( the binding for the admin interface stay in 127.0.0.1)
can someone help me i feel lost

**Comment by Zoey2936** [comment]
Please send your compose file
