### ISSUE TITLE
Nginx module compilation options in NPM Plus.

### ISSUE THREAD

**Issue by PCBiS** [ZoeyVid/NPMplus#521]
Hello, I am using NPMPlus well. Recently, I tried to use Prometheus' nginx-prometheus-exporter to monitor traffic entering and leaving NPMPlus, but the ngx_http_stub_status_module module was disabled, so monitoring was not possible. Therefore, if there is a next patch scheduled, I would like to ask if you could compile the module in Nginx starting from the next patch version.

**Comment by Zoey2936** [comment]
Done with #522 will be released soon

**Comment by dalso0418** [comment]
https://github.com/nginxinc/nginx-prometheus-exporter

For nginx, it seems to be monitoring /stub_status port 8080, but how do I use it per proxy host on npmplus??
