### ISSUE TITLE
Log config geht nicht 

### ISSUE THREAD

**Issue by Easton97-Jens** [ZoeyVid/NPMplus#551]
moin 
ich habe nach der anleiteung unter den discussions die config gesetzt in dem fad /data/ngnix/log.conf die wird bei einem neustart gelert so das kein inhalt mehr drin ist. Wenn ich sie neu erstelle kann ich sie in docker mir anschauen und sehe auch den gleichen inhalt nur nich nach einem neustart.

Wie kann ich trotdem den access_log setzen sodas ich das für auswertung für crowdsec  und andere sachen verwenden kann
sonst bin ich mit disem nginx proxy manager zufrinder wie mit dem anderen den es noch gibt

**Comment by Zoey2936** [comment]
nutzt du die neust version?
