### ISSUE TITLE
Password Authentication does not work after migration

### ISSUE THREAD

**Issue by mercurystorm** [ZoeyVid/NPMplus#553]
I migrated from jc21 docker image of nginx-proxy-manager (using mariadb as my database) 

Migration was pretty seamless but have run into 2-3 issues

First issue:

I have a website set to use "Access List" which was just a basic username / password - Website could be accessed but after being prompted for username and password I would get a 403 error

Looking at docker logs:

2023/12/30 23:36:50 [error] 9497#9497: *3220 open() "/data/etc/access/1" failed (2: No such file or directory), client: 95.183.53.46, server: ***.****.**, request: "GET / HTTP/2.0", host: "***.****.**"
2023/12/30 23:36:50 [error] 9497#9497: *3220 access forbidden by rule, client: 95.183.53.46, server: ***.****.**, request: "GET / HTTP/2.0", host: "***.****.**"
2023/12/30 23:36:50 [error] 9497#9497: *3220 open() "/data/etc/access/1" failed (2: No such file or directory), client: 95.183.53.46, server: ***.****.**, request: "GET /favicon.ico HTTP/2.0", host: "***.****.**", referrer: "https://***.****.**/"
2023/12/30 23:36:50 [error] 9497#9497: *3220 access forbidden by rule, client: 95.183.53.46, server: ***.****.**, request: "GET /favicon.ico HTTP/2.0", host: "***.****.**", referrer: "https://***.****.**/"

(Domain *** out for security) - Deleting the access list and recreating it fixed the error and password authentication now works again

**Comment by Zoey2936** [comment]
can't reproduce: I've setup jc21 with an access list, then migrated to NPMplus, and the file was correctly moved, the config correctly changed and the test also worked
