### ISSUE TITLE
[BUG] HTTP Basic Authentication Popup Not Displaying

### ISSUE THREAD

**Issue by Paillat-dev** [ZoeyVid/NPMplus#564]
**Expected Behavior:**
When accessing a proxy host that is protected by an Access List using HTTP Basic Authentication, a login popup should appear, prompting the user for credentials.

**Actual Behavior:**
Instead of showing the login popup, the server immediately returns a 403 Unauthorized error. No opportunity is provided to enter authentication credentials.

**Steps to Reproduce:**
1. Set up an Access List with HTTP Basic Authentication.
2. Assign this Access List to a proxy host in the server configuration.
3. Attempt to access the proxy host from a web browser.
4. Observe that the server returns a 403 Unauthorized error without displaying the HTTP Basic Authentication popup.

**Additional Information:**
- NPMPlus version: 2.10.4+711d378
- Browser(s) tested: Edge, Firefox

**Log Entry:**
```
2024/01/08 00:56:32 [error] 36828#36828: *62671 access forbidden by rule, client: 10.0.0.2, server: domain.tld, request: "GET / HTTP/2.0", host: "domain.tld"
```

**Comment by Zoey2936** [comment]
Can you please send screenshots of your access list configuration?

**Comment by Paillat-dev** [comment]
Sure:
![image](https://github.com/ZoeyVid/NPMplus/assets/75439456/b8e5b81c-d298-4d92-9226-dfdf40faf77a)
![image](https://github.com/ZoeyVid/NPMplus/assets/75439456/0a8e1e56-8248-4d50-a26d-f358f348bd73)
![image](https://github.com/ZoeyVid/NPMplus/assets/75439456/0bdb7f38-4ce1-433b-87ab-48989c835149)

**Comment by Zoey2936** [comment]
If you don't use ip based authentication, you need to enable "allow access if at least one ..."

**Comment by Paillat-dev** [comment]
> If you don't use ip based authentication, you need to enable "allow access if at least one ..."

Are you sure about that? I actually did so (and denied all in IP auth) and still nothing was showing up. I will continue investigating  on my side.

**Comment by Paillat-dev** [comment]
Ok. For some reason rebooting the container did not help, but it worked with my config after reboot of the whole server. If this can help anyone, tough I would have preferred actually finding the root cause.
