### ISSUE TITLE
certbot.errors.AuthorizationError: Some challenges have failed.

### ISSUE THREAD

**Issue by Paillat-dev** [ZoeyVid/NPMplus#567]
I know this is boring etc.. but I honestly don't know how to fix this.

When creating a certificate for a website, It just dosen't work. The logs are as follows:
```
{
  "identifier": {
    "type": "dns",
    "value": "paillat.is-a.dev"
  },
  "status": "invalid",
  "expires": "2024-01-17T13:01:05Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "invalid",
      "error": {
        "type": "urn:ietf:params:acme:error:connection",
        "detail": "2001:1600:13:101::80: Fetching http://paillat.is-a.dev/.well-known/acme-challenge/5O9bZP-[REDACTED]: Timeout after connect (your server may be slow or overloaded)",
        "status": 400
      },
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/[REDACTED]/[REDACTED]",
      "token": "[REDACTED]",
      "validationRecord": [
        {
          "url": "http://paillat.is-a.dev/.well-known/acme-challenge/[REDACTED]",
          "hostname": "paillat.is-a.dev",
          "port": "80",
          "addressesResolved": [
            "195.15.206.152",
            "2001:1600:13:101::80"
          ],
          "addressUsed": "2001:1600:13:101::80"
        }
      ],
      "validated": "2024-01-10T13:01:05Z"
    }
  ]
}
2024-01-10 14:02:35,864:DEBUG:acme.client:Storing nonce: [REDACTED]
2024-01-10 14:02:35,865:INFO:certbot._internal.auth_handler:Challenge failed for domain paillat.is-a.dev
2024-01-10 14:02:35,865:INFO:certbot._internal.auth_handler:http-01 challenge for paillat.is-a.dev
2024-01-10 14:02:35,865:DEBUG:certbot._internal.display.obj:Notifying user:
Certbot failed to authenticate some domains (authenticator: webroot). The Certificate Authority reported these problems:
  Domain: paillat.is-a.dev
  Type:   connection
  Detail: 2001:1600:13:101::80: Fetching http://paillat.is-a.dev/.well-known/acme-challenge/[REDACTED]: Timeout after connect (your server may be slow or overloaded)

Hint: The Certificate Authority failed to download the temporary challenge files created by Certbot. Ensure that the listed domains serve their content from the provided --webroot-path/-w and that files created there can be downloaded from the internet.

2024-01-10 14:02:35,866:DEBUG:certbot._internal.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/usr/local/certbot/lib/python3.12/site-packages/certbot/_internal/auth_handler.py", line 108, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, max_time_mins, best_effort)
  File "/usr/local/certbot/lib/python3.12/site-packages/certbot/_internal/auth_handler.py", line 212, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.

2024-01-10 14:02:35,867:DEBUG:certbot._internal.error_handler:Calling registered functions
2024-01-10 14:02:35,867:INFO:certbot._internal.auth_handler:Cleaning up challenges
2024-01-10 14:02:35,867:DEBUG:certbot._internal.plugins.webroot:Removing /tmp/acme-challenge/.well-known/acme-challenge/[REDACTED]
2024-01-10 14:02:35,867:DEBUG:certbot._internal.plugins.webroot:All challenges cleaned up
2024-01-10 14:02:35,867:DEBUG:certbot._internal.log:Exiting abnormally:
```

I don't see any reason, apart from the fact that the /.well-known path is not being correctly served, but it should with the include of the `acme-challenge.conf`.

I am running the latest docker image, with crowdsec enabled.
Any help would be much appreciated

**Comment by Zoey2936** [comment]
please run: `docker exec npmplus echo "abc" | tee /tmp/acme-challenge/abc`
and then `curl -skL http://paillat.is-a.dev/.well-known/acme-challenge/abc`

**Comment by Paillat-dev** [comment]
Got an error
```bash
curl skL http://paillat.is-a.dev/.well-known/acme-challenge/abc
curl: (6) Could not resolve host: skL
```

**Comment by Zoey2936** [comment]
I've edited my comment please retry

**Comment by Paillat-dev** [comment]
It returns
```
http://paillat.dev
```
Wich is the website that is set in the redirect host is set to point to.

**Comment by Zoey2936** [comment]
did you tried the server reachability check?

**Comment by Paillat-dev** [comment]
> did you tried the server reachability check?

Yes I did and It succeded.

**Comment by Paillat-dev** [comment]
It used to work sometimes only but not always, I would say 1 out of 5 times the challenge would work but now it stopped working completely, and I started usng dns challenge, but this time I can't since I am not the one in control of the dns zone.

**Comment by Zoey2936** [comment]
https://github.com/is-a-dev/register/pull/11053 I will try to reproduce

**Comment by Zoey2936** [comment]
do you have ipv6 correctly configured on your system and in your nameservers?

**Comment by Paillat-dev** [comment]
> do you have ipv6 correctly configured on your system and in your nameservers?

I did make sure to set it up, but I will doublecheck again.

**Comment by Zoey2936** [comment]
I ask because:
```console
zoey@mx:~$ curl http://paillat.dev -6I
curl: (7) Failed to connect to paillat.dev port 80 after 311 ms: Couldn't connect to server
zoey@mx:~$ curl http://paillat.dev -4I
HTTP/1.1 301 Moved Permanently
Connection: keep-alive
Content-Length: 162
Server: GitHub.com
Content-Type: text/html
Location: https://paillat.dev/
X-GitHub-Request-Id: CC8E:2E18B3:5D81A14:5EE5B3A:65A1A644
Accept-Ranges: bytes
Date: Fri, 12 Jan 2024 20:51:58 GMT
Via: 1.1 varnish
Age: 41
X-Served-By: cache-fra-eddf8230068-FRA
X-Cache: HIT
X-Cache-Hits: 1
X-Timer: S1705092719.926596,VS0,VE2
Vary: Accept-Encoding
X-Fastly-Request-ID: c13bf9e9bc487c23e5e7c14ac6f5484c151b3ecb
```

**Comment by Paillat-dev** [comment]
> I ask because:
> 
> ```
> zoey@mx:~$ curl http://paillat.dev -6I
> curl: (7) Failed to connect to paillat.dev port 80 after 311 ms: Couldn't connect to server
> zoey@mx:~$ curl http://paillat.dev -4I
> HTTP/1.1 301 Moved Permanently
> Connection: keep-alive
> Content-Length: 162
> Server: GitHub.com
> Content-Type: text/html
> Location: https://paillat.dev/
> X-GitHub-Request-Id: CC8E:2E18B3:5D81A14:5EE5B3A:65A1A644
> Accept-Ranges: bytes
> Date: Fri, 12 Jan 2024 20:51:58 GMT
> Via: 1.1 varnish
> Age: 41
> X-Served-By: cache-fra-eddf8230068-FRA
> X-Cache: HIT
> X-Cache-Hits: 1
> X-Timer: S1705092719.926596,VS0,VE2
> Vary: Accept-Encoding
> X-Fastly-Request-ID: c13bf9e9bc487c23e5e7c14ac6f5484c151b3ecb
> ```

That is hosted on github pages currently, I did not move it yet, and what I had in npmplus was a redirect to it, wich worked without ssl.

**Comment by Paillat-dev** [comment]
And yes, ipv6 was indeed set up.

**Comment by Zoey2936** [comment]
can you maybe start npmplus again? I want to try to curl it from outside and test ipv6

**Comment by Paillat-dev** [comment]
> can you maybe start npmplus again? I want to try to curl it from outside and test ipv6

Yup, it just crashed because of some other error and I saw it restarting myself.

**Comment by Zoey2936** [comment]
```console
zoey@mx:~$ curl [2001:1600:13:101::80]
curl: (7) Failed to connect to 2001:1600:13:101::80 port 80 after 9 ms: Couldn't connect to server
zoey@mx:~$ curl 195.15.206.152
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>NPMplus</center>
</body>
</html>
```
seems to be wrong configured ipv6

**Comment by Paillat-dev** [comment]
https://github.com/moby/moby/issues/24379

Honestly I'll just disable ipv6 completely and everywhere at this point and see. I don't wanna spend moore time trying to fix this. I'll let you know if it fixes the issue (I have a feeling it will)

**Comment by Zoey2936** [comment]
does it work now? (do you use network mode host?)

**Comment by Paillat-dev** [comment]
> does it work now? (do you use network mode host?)

I just disabled iv6 in my dns. I didn't have time to mess witht his more and it works with ipv4, the issue being that swarm does not support ipv6 on the ingress network. The solution I came up with and will probably setup when I have time is have some service on the host forward ipv6 trafic to localhost to npmplus's port.

**Comment by Paillat-dev** [comment]
So yes it works
