### ISSUE TITLE
Error 502 Bad Gateway after migrating from NPM to NPMplus

### ISSUE THREAD

**Issue by Joly0** [ZoeyVid/NPMplus#583]
Hey, i swaped out my NPM container for NPMplus in Unraid, afterwards i only get 502 errors for all my websites. 
I have my domain on cloudflare and i am using cloudflare tunnel to directly connect to the cloudflared container running on my unraid server aswell. 
This worked no problem for NPM, but something is buggy with NPMplus here. Not sure were to pinpoint this, so i am opening an issue here now.

**Comment by Zoey2936** [comment]
Please send the docker logs

**Comment by Joly0** [comment]
Nvm, i found the issue. My cloudflare tunnel was configured wrong and had the old hostname of NPM still as the configured proxy instead of npmplus.

**Comment by Joly0** [comment]
Btw, as there is none, i am creating a template for npmplus for unraid, so others can use your container aswell there easily

**Comment by Zoey2936** [comment]
Sounds good
