### ISSUE TITLE
TZ invalid or unset

### ISSUE THREAD

**Issue by Some1OnLine** [ZoeyVid/NPMplus#592]
I tried the UnRaid Docker Package and when I set the timezone to America/Los_Angeles the WebUI never comes up and when I look it in the log it says the TZ is invalid or not set. If I set it back to Europe/Berlin everything seems to come up just fine.

Edit : Better clarification

**Comment by Zoey2936** [comment]
To what do you set it?

**Comment by Some1OnLine** [comment]
America/Los_Angeles

atm, its set to Europe/Berlin so it would at least start and let me into the webui etc.. But so far looks sexy! I wanna play with it some more. :)

minor correction. the docker container starts and stays started. but webui never comes up. log file shows that TZ is unset or invalid. if I switch it back to Europe/Berlin everything starts up and seems to work just fine. I have yet to test much further. but want to.

**Comment by Zoey2936** [comment]
will be fixed in the next release

**Comment by Zoey2936** [comment]
fixed in latest release
