### ISSUE TITLE
Nice Project

### ISSUE THREAD

**Issue by honestlai** [ZoeyVid/NPMplus#594]
I like this project, and really appreciate the gui interface being run behind https, but noticed that when I tried to run my current stack of web apps through it, I wasn't able to get the apps to run correctly, rendering of certain things would not work... like emby. It shows my category of media, but none of the menus for recently played or being able to pick a show/movie renders on the page.

Also, when I try to save and/or change an entry, I often got an error on the save of the new proxy, but without any text... I can only see a small red bar at the top of the save area

<img width="523" alt="image" src="https://github.com/ZoeyVid/NPMplus/assets/72324013/bf9cbd70-67c6-427c-92a1-e3482677b919">

**Comment by Zoey2936** [comment]
Please send the docker logs, the configuration, a screenshot of the wrong renderd page etc.

**Comment by Zoey2936** [comment]
could be fixed by latest releases, if not please reopen
