### ISSUE TITLE
NPM Migration support

### ISSUE THREAD

**Issue by hausner** [ZoeyVid/NPMplus#595]
Is it possible to migrate from NPM "Classic" to "Plus"? Or do you need to set it up from scratch?
Im running NPM with a MariaDB connection.

**Comment by Zoey2936** [comment]
create a backup, read the migration guide in the readme and then just switch the image

**Comment by hausner** [comment]
I totally missed the migration section. Sorry :-)

**Comment by hausner** [comment]
I totally missed the migration section. Sorry :-)
