### ISSUE TITLE
GoAccess does not start

### ISSUE THREAD

**Issue by rmsag** [ZoeyVid/NPMplus#599]
Hello everyone

I think the project is great and installed it straight away.
I followed this readme: #575 

NPMplus starts and GoAccess doesn't start, I don't see anything in the log that is incorrect. Is this a bug or what else needs to be changed? So that my GoAccess starts?

I included the line
`  - GOA_IPV4_BINDING=127.0.0.1 # IPv4 address to bind for the goaccess, defaults to all`

**Comment by Zoey2936** [comment]
please send your full compose file

**Comment by rmsag** [comment]
many thanks for the quick response!
Here is my Portainer stack config.

I hope you don't tell me straight away that I made the mistake... :) 

[npmplus.txt](https://github.com/ZoeyVid/NPMplus/files/14023036/npmplus.txt)

sorry, I have the file as an attachment, as soon as I upload it as code the formatting is no longer correct

**Comment by Zoey2936** [comment]
you need to uncomment `GOA=true`

**Comment by rmsag** [comment]
Thank you! So my mistake after all!
GOA is now running and I assume that geoipupdate is now also running. I have the *.mmdb files in the directory "/opt/npm/etc/goaccess/geoip"

Are you still seeing an error why Crowdsec cannot be accessed?
I get the following message.

![image](https://github.com/ZoeyVid/NPMplus/assets/58624847/3acb174b-3a1c-480c-8425-8b973b1017c0)

My crowdsec.conf
[crow.txt](https://github.com/ZoeyVid/NPMplus/files/14023999/crow.txt)

Ps. can we buy you a coffee? for the support :)

**Comment by Zoey2936** [comment]
please send your docker logs of crowdsec and npmplus

> Ps. can we buy you a coffee? for the support :)

thanks but currently not, maybe in the future, I will mention it in the release notes if I/we accept donations maybe in the future, but as I said, currently not

**Comment by rmsag** [comment]
Great thank you!

NPMplus-Log
[npmplus-log.txt](https://github.com/ZoeyVid/NPMplus/files/14024357/npmplus-log.txt)


Crowdsec-Log
[crowdsec-log.txt](https://github.com/ZoeyVid/NPMplus/files/14024326/crowdsec-log.txt)

Then I'll wait for the notes. ;)

**Comment by Zoey2936** [comment]
you either need to fill out:
CAPTCHA_PROVIDER=
SECRET_KEY=
SITE_KEY=
in your crowdsec bouncer config or you could try to set:
BOUNCING_ON_TYPE=ban

**Comment by rmsag** [comment]
Thanks!

I have now configured Captcha using turnstile. But the web interface cannot be accessed at https://ip:8080. It should work now, right?
Here again are my logs from NPMplus:

[_npmplus_logs.txt](https://github.com/ZoeyVid/NPMplus/files/14028300/_npmplus_logs.txt)

Sorry for causing so much trouble.

**Comment by Zoey2936** [comment]
There is no ui

**Comment by rmsag** [comment]
Sorry, I'm stupid! Port 8080 is for the API
But everything works now!
Thank you very much for the incredibly fast and reliable support!
