### ISSUE TITLE
MOZILLA_PKIX_ERROR_REQUIRED_TLS_FEATURE_MISSING

### ISSUE THREAD

**Issue by Joly0** [ZoeyVid/NPMplus#601]
Hey, i keep getting the above error when i try to connect to any website behind npmplus through firefox.

![grafik](https://github.com/ZoeyVid/NPMplus/assets/13993216/1b29c162-0a95-42d1-b301-7eb2b6293be7)

Here is the docker logs:
```
nginx: [warn] "ssl_stapling" ignored, issuer certificate not found for certificate "/data/tls/dummycert.pem"
nginx: [warn] "ssl_stapling" ignored, issuer certificate not found for certificate "/data/tls/dummycert.pem"
nginx: [warn] "ssl_stapling" ignored, issuer certificate not found for certificate "/data/tls/dummycert.pem"
2024/01/23 18:40:25 [warn] 754#754: "ssl_stapling" ignored, issuer certificate not found for certificate "/data/tls/dummycert.pem"
2024/01/23 18:40:25 [warn] 754#754: "ssl_stapling" ignored, issuer certificate not found for certificate "/data/tls/dummycert.pem"
2024/01/23 18:40:25 [warn] 754#754: "ssl_stapling" ignored, issuer certificate not found for certificate "/data/tls/dummycert.pem"
```

**Comment by Zoey2936** [comment]
do you run a local instance?

**Comment by Joly0** [comment]
Found the issue. Its right there in the text. There are some leftover "dummycert.pem" files from npm. Not sure, why they are there, but i deleted them and now its working

**Comment by Zoey2936** [comment]
> do you run a local instance?

**Comment by Joly0** [comment]
Ok, i have to reopen this, as it is happening again. The dummycert.pem and dummykey.pem file appeared again. But deleting them didnt help this time. Additionaly, since switching to npmplus i cant access my jellyfin instance anymore. I always receive error code 400

**Comment by Joly0** [comment]
> do you run a local instance?

What exactly do you mean by "local instance"?

**Comment by Zoey2936** [comment]
do you access it using an private ip / domain that rewrites to a private ip

**Comment by Joly0** [comment]
Still not 100% sure what you mean, but i´ll try to explain. So i have npmplus and jellyfin on my homeserver. I have my pihole configured for local dns so when i access jellyfin.mydomain.de it returns the home server ip. But i already tested it without that route over pihole

**Comment by Zoey2936** [comment]
see README.md:
> Note: Internal/LAN Instance? Please disable must-staple in /opt/npm/tls/certbot/config.ini.

**Comment by Joly0** [comment]
> see README.md:
> 
> > Note: Internal/LAN Instance? Please disable must-staple in /opt/npm/tls/certbot/config.ini.

Will try that

**Comment by Joly0** [comment]
Ok, looks like that helped. Also the error 400 was caused by adding this proxy header "proxy_set_header Host $host;"
Though i am not sure, why this now only happens with npmplus and didnt with npm, but nontheless, its working now

**Comment by Zoey2936** [comment]
can I close?

**Comment by Joly0** [comment]
Btw, this error is happening again, although i set "must-staple = false" in config.ini

**Comment by Zoey2936** [comment]
did you just set it to false or did you also recreated your certs after that? (not renewed but recreated)

**Comment by Joly0** [comment]
I have one certbot certificate, which i renewed after setting it to false. But it doesnt say anywere in the readme to reacreate them, does it? The readme only mention custom certificates `if you use custom certificates, you need to upload the CA/Intermediate Certificate (file name: chain.pem) in the /opt/npm/tls/custom/npm-[certificate-id] folder`

**Comment by Zoey2936** [comment]
I've added it to the readme

**Comment by Joly0** [comment]
Ok, but now i keep getting this, when i try to set this new certificate for my proxy hosts and save it:
![grafik](https://github.com/ZoeyVid/NPMplus/assets/13993216/e8d4fb92-a5f4-4396-bf6e-b0230361ed9d)

```
nginx: [emerg] cannot load certificate "/data/tls/certbot/live/npm-11/fullchain.pem": BIO_new_file() failed (SSL: error:80000002:system library::No such file or directory:calling fopen(/data/tls/certbot/live/npm-11/fullchain.pem, r) error:10000080:BIO routines::no such file)
nginx: configuration file /usr/local/nginx/conf/nginx.conf test failed
```

**Comment by Zoey2936** [comment]
"No such file or directory"

**Comment by Joly0** [comment]
Restarted Container, and its not working anymore. In docker logs its stuck here:

```
----------------------------------------------------------
Let's Encrypt certificates cleanup - 2024/02/04 14:15:57
----------------------------------------------------------
Keeping /data/tls/certbot/archive/npm-10/cert4.pem.
Keeping /data/tls/certbot/archive/npm-10/chain4.pem.
Keeping /data/tls/certbot/archive/npm-10/fullchain4.pem.
Keeping /data/tls/certbot/archive/npm-10/privkey4.pem.
Keeping /data/tls/certbot/archive/npm-13/cert1.pem.
Keeping /data/tls/certbot/archive/npm-13/chain1.pem.
Keeping /data/tls/certbot/archive/npm-13/fullchain1.pem.
Keeping /data/tls/certbot/archive/npm-13/privkey1.pem.
8 file(s) kept.
0 file(s) deleted.
no DEFAULT_CERT_ID set, using dummycerts.
Working on file: /data/nginx/custom/events.conf
Working on file: /data/nginx/custom/http.conf
Working on file: /data/nginx/custom/http_top.conf
Working on file: /data/nginx/custom/root.conf
Working on file: /data/nginx/custom/server_dead.conf
Working on file: /data/nginx/custom/server_proxy.conf
Working on file: /data/nginx/custom/server_redirect.conf
Working on file: /data/nginx/custom/server_stream.conf
Working on file: /data/nginx/custom/server_stream_tcp.conf
Working on file: /data/nginx/custom/server_stream_udp.conf
Working on file: /data/nginx/custom/stream.conf
Working on file: /data/nginx/custom/stream_top.conf
Working on file: /data/nginx/default.conf
Working on file: /data/nginx/ip_ranges.conf
Working on file: /data/nginx/proxy_host/1.conf
Working on file: /data/nginx/proxy_host/11.conf
Working on file: /data/nginx/proxy_host/12.conf
Working on file: /data/nginx/proxy_host/2.conf
Working on file: /data/nginx/proxy_host/3.conf
Working on file: /data/nginx/proxy_host/5.conf
Working on file: /data/nginx/proxy_host/8.conf
Success.
usermod: no changes

-------------------------------------
 _ _  ___  __ __       _
| \ || . \|  \  \ ___ | | _ _  ___
|   ||  _/|     || . \| || | |[_-[
|_\_||_|  |_|_|_||  _/|_| \__|/__/
                 |_|
-------------------------------------
Version:  2.11.1+a779df8
Date:     Sun Feb  4 14:15:57 CET 2024
User:     npm
PUID:     99
User ID:  99
PGID:     100
Group ID: 100
-------------------------------------


```

And the admin page isnt loading anymore

**Comment by Joly0** [comment]
> "No such file or directory"

Yes, i saw that aswell and the file it is searching isnt there. I just deleted the old certificate and added a new one through certbot

**Comment by Zoey2936** [comment]
you wrote your own error
if you delete the cert, then nginx can't find it....

**Comment by Zoey2936** [comment]
run `rm -v /opt/nginx/proxy_host/*`, restart npmplus, open npmplus on port 81, then create your cert, then update all your hosts with the new cert
