### ISSUE TITLE
Access List combined with crowdsec does not work

### ISSUE THREAD

**Issue by CodeScreamy** [ZoeyVid/NPMplus#617]
I also discovered your app on the Unraid store. The features are great and I want a Crowdsec options.

The following settings are used:
![grafik](https://github.com/ZoeyVid/NPMplus/assets/157902357/da367c42-9492-492b-abd9-0f668f2dad9c)
![grafik](https://github.com/ZoeyVid/NPMplus/assets/157902357/38044d61-0972-452a-bc98-f7c26ffab1eb)

Before in NPM everything works. I get a Login Dialog before I can access my service.
![grafik](https://github.com/ZoeyVid/NPMplus/assets/157902357/107f542f-511e-4d4e-9d1a-4b62b4a3c8ec)

**It does not work for me in NPMplus.** Can you help me? It is a bug or have I done something wrong?

**Comment by Zoey2936** [comment]
What does not work?

**Comment by CodeScreamy** [comment]
This dialog is not there, the Authentication Popup not displaying:

![300188084-107f542f-511e-4d4e-9d1a-4b62b4a3c8ec](https://github.com/ZoeyVid/NPMplus/assets/157902357/ffccc0e1-d77c-4ac3-a2a0-15897630fa77)

I use NPMplus as Docker in Unraid. The problem seems to be a bit similar to this https://github.com/ZoeyVid/NPMplus/issues/564

Expected Behavior:
When accessing a proxy host that is protected by an Access List using HTTP Basic Authentication, a login popup should appear, prompting the user for credentials.

Actual Behavior:
Instead of showing the login popup, the server **immediately direct to the proxy host**. No opportunity is provided to enter authentication credentials.

Steps to Reproduce:

- Set up an Access List with HTTP Basic Authentication.
- Assign this Access List to a proxy host in the server configuration.
- Attempt to access the proxy host from a web browser.
- Observe that the server  immediately direct to the proxy host **without displaying the HTTP Basic Authentication popup**.

Additional Information:

- NPMPlus version: 2.11.1+411b2a6
- Browser(s) tested: Chrome, Firefox

**Comment by Zoey2936** [comment]
can confirm, I will try to fix it

**Comment by Zoey2936** [comment]
you use crowdsec right?

**Comment by Zoey2936** [comment]
if yes please try without it

**Comment by Zoey2936** [comment]
https://github.com/crowdsecurity/lua-cs-bouncer/issues/61

**Comment by CodeScreamy** [comment]
> if yes please try without it

Yes I use crowdsec. If I deactivate crowdsec it works as expected.
I hope in the future and crowdsec and HTTP Basic Authentication works better together.

Thanks very much for inspecting the problem.

**Comment by Zoey2936** [comment]
Seems to be a bug if crowdsec as mentioned - nothing I can fix....

**Comment by Zoey2936** [comment]
will be fixed in the next release, please reopen if it still not work in the next release (will release in a few hours)

**Comment by CodeScreamy** [comment]
Thank you very much👍. I will test it directly this weekend.

**Comment by CodeScreamy** [comment]
It works! Thank you very much.

**Comment by Zoey2936** [comment]
I've did nothing, I've just reported the bug and updated NPMplus to the patched version
