### ISSUE TITLE
feature request: passing access logs to crowdsec

### ISSUE THREAD

**Issue by darkclip** [ZoeyVid/NPMplus#630]
I'm coming from old npm, and I have to say great job fixing all those bugs and adding new features.
It has crowdsec support, but the access logs are disabled by default.
Seems the only way to output access logs is to go through each proxied site individually, and also there's no easy way to get stream logs.
It would be nice to have option to easily open access logs.

possible solution:
set for nginx.conf:
```
error_log /var/log/nginx/error.log;
access_log /var/log/nginx/access.log;
``` 

in startup script check for env variables
set
```
ln -sf /dev/null /var/log/nginx/error.log
ln -sf /dev/null /var/log/nginx/access.log
```
or
```
ln -sf /dev/stdout /var/log/nginx/error.log
ln -sf /dev/stdout /var/log/nginx/access.log
```
or leave the log files as is.

**Comment by darkclip** [comment]
possible solution:
set for nginx.conf:
```
error_log /var/log/nginx/error.log;
access_log /var/log/nginx/access.log;
``` 

in startup script check for env variables,
set
```
ln -sf /dev/null /var/log/nginx/error.log
ln -sf /dev/null /var/log/nginx/access.log
```
or
```
ln -sf /dev/stderr /var/log/nginx/error.log
ln -sf /dev/stdout /var/log/nginx/access.log
```

**Comment by Zoey2936** [comment]
see compose.yaml
