### ISSUE TITLE
Add Authentik for identity access management and into crowdsec logs ingestion/bouncer

### ISSUE THREAD

**Issue by TheLinuxGuy** [ZoeyVid/NPMplus#639]
Could you consider including Authentik IdP on your docker-compose stack? https://goauthentik.io

I'm fairly new to reverse proxies and crowdsec; but my understanding is that crowdsec (already integrated in NPMplus) needs a configuration change to read the authentic logs and for the bouncer to ban IPs that are attempting to bruteforce things.

Authentik can allow a user to sign on once and be logged into all apps (radar,sonar, etc) it looks great. Found some great tutorials on this channel going deep on the rabbit hole on the many things that Authentik can do... https://www.youtube.com/watch?v=S-CIGno0cdw

**Comment by Zoey2936** [comment]
sorry but NPMplus only contains the crowdsec bouncer, if you want to use it to parse logs, please refer to their documentation and forums, etc.

**Comment by TheLinuxGuy** [comment]
> sorry but NPMplus only contains the crowdsec bouncer, if you want to use it to parse logs, please refer to their documentation and forums, etc.

thanks for the reply and the great software.

Do you mean to say that it should be OK to modify all items inside `crowdsec` folder and its configuration? The only thing that NPMplus does different is that upon startup of the container if crowdsec configuration does not exist it creates it for me else I can put whatever I want in the folder and it would work just as a standalone crowdsec standalone countainer app?

**Comment by Zoey2936** [comment]
crowdsec has two parts:
- bouncers
- log parses/collections

NPMplus just contains the bouncers and blocks a request
if you want to check a log for bad entries that is nothing I can help you since it has nothing to do with NPMplus

and yes you can edit every mounted file
