### ISSUE TITLE
Typo in  NGINX_DIABLE_PROXY_BUFFERING

### ISSUE THREAD

**Issue by Nihimia** [ZoeyVid/NPMplus#649]
Hello

Thank you for this project !

It seems that NGINX_DIABLE_PROXY_BUFFERING have a typo, and it should be NGINX_DISABLE_PROXY_BUFFERING instead. 

It works because the typo is present each time it is called., but brings some confusion when using it in docker compose file.

**Comment by Zoey2936** [comment]
ohh thanks! I will release a patch

**Comment by Zoey2936** [comment]
patch is release
