### ISSUE TITLE
Empty ip_ranges.conf

### ISSUE THREAD

**Issue by Nihimia** [ZoeyVid/NPMplus#655]
Hi !

No matter what value I put in SKIP_IP_RANGES (true/false or even commented), the file ip_ranges.conf stay empty.

So I tried to start a new container, with minimal settings : 

```docker
version: "3"
services:
  npmplus:
    container_name: npmtest
    image: zoeyvid/npmplus
    restart: always
    network_mode: host
    volumes:
      - "/docker/test/data:/data"
    environment:
      - "TZ=Europe/Paris" # set timezone, required
 ```
As the defaut value for SKIP_IP_RANGES is false, this should fill the ip_ranges.conf file. But that's not the case.

I do not see any errors in the console logs, I am not even sure the instructions for ip_ranges are processed, as I see nothing related to that in the console log.

I tried to start an older version (373), and it work. 

Thank you ! :)

**Comment by Zoey2936** [comment]
Please try the develop tag

**Comment by Nihimia** [comment]
Yes, it works with develop tag, thank you ! :+1: 

Don't know if it's the expected behaviour, but starting npmplus without SKIP_IP_RANGES set (or set to false) it download and apply the ip_ranges as it should.
But, setting SKIP_IP_RANGES to true later does not clean ip_ranges.conf file, and the previously downloaded file stay persistent.  Maybe it should be better to empty that file if the value is set to true ?

**Comment by Zoey2936** [comment]
please try again with the develop tag

**Comment by Nihimia** [comment]
Nice, it works too !

Thank you for your help and your work on this project.

**Comment by Zoey2936** [comment]
I will release this fix later

**Comment by Nihimia** [comment]
Hum, I was looking at ip_ranges.js, it seems that process.env.SKIP_IP_RANGES === false in initTimer needs to be changed as you did with process.env.SKIP_IP_RANGES == 'false'

I can see in my console the logger info "Fetching IP Ranges from online services..." that you previously fixed, but can't see "IP Ranges Renewal Timer initialized" from initTimer.

```bash
[Global   ] › ℹ  info      Using Sqlite: /data/etc/npm/database.sqlite
[Migrate  ] › ℹ  info      Current database version: none
[IP Ranges] › ℹ  info      Fetching IP Ranges from online services...
[IP Ranges] › ℹ  info      Fetching https://ip-ranges.amazonaws.com/ip-ranges.json
[IP Ranges] › ℹ  info      Fetching https://www.cloudflare.com/ips-v4
[IP Ranges] › ℹ  info      Fetching https://www.cloudflare.com/ips-v6
[SSL      ] › ℹ  info      Certbot Renewal Timer initialized
[Global   ] › ℹ  info      Backend PID 442 listening on port 48693 ...
[Nginx    ] › ℹ  info      Starting Nginx
```

**Comment by Zoey2936** [comment]
Ohh yes, will be done

**Comment by Zoey2936** [comment]
I've released now, you can switch back to the latest tag

**Comment by Nihimia** [comment]
Hello,

Thank you, can confirm everything is working great !

Just about the renewal task : 

```docker
2024/02/20 03:05:05 [error] 1213#1213: [lua] crowdsec.lua:57: init(): error loading captcha plugin: no recaptcha site key provided, can't use recaptcha
2024/02/20 03:05:05 [alert] 1213#1213: [lua] crowdsec.conf:3):8: [Crowdsec] Initialisation done
[IP Ranges] › ℹ  info      Fetching IP Ranges from online services...
[IP Ranges] › ℹ  info      Fetching https://ip-ranges.amazonaws.com/ip-ranges.json
[SSL      ] › ℹ  info      Renewing TLS certs close to expiry...
[IP Ranges] › ℹ  info      Fetching https://www.cloudflare.com/ips-v4
[IP Ranges] › ℹ  info      Fetching https://www.cloudflare.com/ips-v6
[Nginx    ] › ℹ  info      Reloading Nginx
[Nginx    ] › ℹ  info      Reloading Nginx
[SSL      ] › ℹ  info      Renew Complete
2024/02/20 04:05:05 [error] 1213#1213: [lua] crowdsec.lua:57: init(): error loading captcha plugin: no recaptcha site key provided, can't use recaptcha
2024/02/20 04:05:05 [alert] 1213#1213: [lua] crowdsec.conf:3):8: [Crowdsec] Initialisation done
2024/02/20 04:05:05 [error] 1213#1213: [lua] crowdsec.lua:57: init(): error loading captcha plugin: no recaptcha site key provided, can't use recaptcha
2024/02/20 04:05:05 [alert] 1213#1213: [lua] crowdsec.conf:3):8: [Crowdsec] Initialisation done
```

nginx is reloaded twice, but it looks more tied on #656
