### ISSUE TITLE
Not able to access the Admin UI

### ISSUE THREAD

**Issue by tobias86aa** [ZoeyVid/NPMplus#665]
Hi

I getting the following error in the logs and nothing really happen after that and i am not able to access the admin UI. 

npmplus  | 2024/02/26 17:46:14 [warn] 448#448: "ssl_stapling" ignored, issuer certificate not found for certificate "/data/tls/dummycert.pem"
npmplus  | 2024/02/26 17:46:14 [notice] 448#448: ModSecurity-nginx v1.0.3 (rules loaded inline/local/remote: 0/14/0)

version: "3"
services:
  npmplus:
    container_name: npmplus
    image: zoeyvid/npmplus
    restart: always
    network_mode: host
    volumes:
      - ./npm:/data
    environment:
      - TZ=Europe/Stockholm # set timezone, required
      - NGINX_LOG_NOT_FOUND=true
      - GOA=true

Did i do something wrong here? 

I did edit the following file:
Note: Internal/LAN Instance? Please disable must-staple in /opt/npm/tls/certbot/config.ini before creating your certificates.

But nothing seems to change here. 

I use Dockeg to deploy this stack.

**Comment by Zoey2936** [comment]
The log lines aren't errors. Do you opened the ports in your firewall?

**Comment by tobias86aa** [comment]
That seems to have work. 

But now when i try to add proxy host and get it setup like i have dont whit the vanilla NPM 

I end up getting follow message on my domain. 

Forbidden

You don't have permission to access this resource.Reason: Cannot perform Post-Handshake Authentication.

**Comment by Zoey2936** [comment]
can you send secreenshots of that error? and of your configuration

**Comment by tobias86aa** [comment]
You can see it yourself here: https://tokar86a.top/

[2.zip](https://github.com/ZoeyVid/NPMplus/files/14410097/2.zip)

I included the file in a zip file.

**Comment by Zoey2936** [comment]
are port 80/tcp, 443/tcp and 443/udp opened in your firewall?

**Comment by tobias86aa** [comment]
![image](https://github.com/ZoeyVid/NPMplus/assets/5478720/ce7afb67-3a0f-4456-b012-8425d25ea4cb)

yes

**Comment by Zoey2936** [comment]
can you send a screenshot of your nginx configuration?

**Comment by Zoey2936** [comment]
```
root@PC-Zoey:~# curl https://tokar86a.top/  -L
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access this resource.Reason: Cannot perform Post-Handshake Authentication.<br /></p>
<script>(function(){var js = "window['__CF$cv$params']={r:'85babe2b0fa95b67',t:'MTcwODk3NzI5Ny4yOTQwMDA='};_cpo=document.createElement('script');_cpo.nonce='',_cpo.src='/cdn-cgi/challenge-platform/scripts/jsd/main.js',document.getElementsByTagName('head')[0].appendChild(_cpo);";var _0xh = document.createElement('iframe');_0xh.height = 1;_0xh.width = 1;_0xh.style.position = 'absolute';_0xh.style.top = 0;_0xh.style.left = 0;_0xh.style.border = 'none';_0xh.style.visibility = 'hidden';document.body.appendChild(_0xh);function handler() {var _0xi = _0xh.contentDocument || _0xh.contentWindow.document;if (_0xi) {var _0xj = _0xi.createElement('script');_0xj.innerHTML = js;_0xi.getElementsByTagName('head')[0].appendChild(_0xj);}}if (document.readyState !== 'loading') {handler();} else if (window.addEventListener) {document.addEventListener('DOMContentLoaded', handler);} else {var prev = document.onreadystatechange || function () {};document.onreadystatechange = function (e) {prev(e);if (document.readyState !== 'loading') {document.onreadystatechange = prev;handler();}};}})();</script></body></html>
```
curl works and it shows js, which isn't added by npmplus so it must be from the upstream

**Comment by tobias86aa** [comment]
So the question is what is adding that.

**Comment by Zoey2936** [comment]
nginx error page looks like this:
```
<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>NPMplus</center>
</body>
</html>
```
so the error comes from your upstream http host

**Comment by tobias86aa** [comment]
But it still feel kind of strange that its working whit the normal NPM manager and not this one.

**Comment by tobias86aa** [comment]
was able to get it to work. Thanks for all the help.
