### ISSUE TITLE
Multiple issues with GOA

### ISSUE THREAD

**Issue by Nihimia** [ZoeyVid/NPMplus#678]
Hello,

This one looks a bit like a part of #673 but it's a little different : 

Every 24h, when logrotate does it job, I have the following errors : 

```docker
GoAccess - version 1.8.1 - Nov 2 2023 19:51:14
Config file: No config file used
Fatal error has occurred
Error occurred at: src/goaccess.c - perform_tail_follow - 846
Unable to open the specified log file '/data/nginx/access.log'. No such file or directory
```
After that, I can't use goaccess anymore and I need to restart the container. Otherwise, when I try to access the goaccess page will throws me : 
```docker
connect() failed (111: Connection refused) while connecting to upstream, client: {CLIENT_IP}, server: _, request: "GET / HTTP1.1", upstream: "http://127.0.0.1:48683/", host: "{DOMAIN}"
```
It looks like goaccess can't track the new access.log when the older one is rotated ?

**Comment by Zoey2936** [comment]
should also be fixed in the next release
