### ISSUE TITLE
Multi language support

### ISSUE THREAD

**Issue by lateautumn233** [ZoeyVid/NPMplus#693]
I have a branch of nginx proxy manager with added support for multiple languages
Perhaps we can also add multilingual support for npmplus?

https://github.com/lateautumn233/nginx-proxy-manager/commits/weblate-nginxproxymanager-nginxproxymanager/

thanks

**Comment by Zoey2936** [comment]
yes, can you please create a PR?

**Comment by lateautumn233** [comment]
Sorry, I have been busy with exams lately. I will try to submit a PR by the end of March

**Comment by Zoey2936** [comment]
many thanks, take the time you need

**Comment by Zoey2936** [comment]
see #731

**Comment by lateautumn233** [comment]
Do we need to continue adding multilingual support to the current version?

**Comment by Zoey2936** [comment]
If you want you can open a PR anytime, but I don't think it will have a long time of usage

**Comment by Zoey2936** [comment]
Hello, I think non php version will exist longer then I thought, so if you want your can open a PR. Or if you give me the permission I can try to merge the language related changes from your fork into NPMplus

**Comment by Zoey2936** [comment]
it seems only json files, cache.json and i18n.js are changed in your fork, correct?

**Comment by lateautumn233** [comment]
> it seems only json files, cache.json and i18n.js are changed in your fork, correct?

yes

**Comment by Zoey2936** [comment]
language is read from browser in your fork? since I don't see that you added a selection box, correct?

**Comment by lateautumn233** [comment]
> language is read from browser in your fork? since I don't see that you added a selection box, correct?


https://github.com/lateautumn233/nginx-proxy-manager/commit/d1aba3aaaa82f1319a8db06e4023ad2c4f0ea6c8#diff-15ad3fa19f477ab316a0d14f11afb2d1181e011f30500905e47013bd4891bcb4R5

**Comment by Zoey2936** [comment]
so this patch file is enough? https://github.com/NginxProxyManager/nginx-proxy-manager/commit/d1aba3aaaa82f1319a8db06e4023ad2c4f0ea6c8.patch and then I can place every language in i18n/\<lang-code\>/messages.json

**Comment by Zoey2936** [comment]
I applied your patch (but also modified it), if you want to add your language see this commit as template: https://github.com/ZoeyVid/NPMplus/commit/a026b42329f66b89fe1fbe5e6034df5d3fc2e11f
