### ISSUE TITLE
Can't use HTTP/3 without enabling HSTS and Security Headers.

### ISSUE THREAD

**Issue by scampower3** [ZoeyVid/NPMplus#696]
Can't use HTTP/3 without enabling HSTS and Security Headers.
When Enable HSTS and Security Headers is disable and Enable HTTP/3 is on, HTTP/3 will be disabled still.
Going back to the settings screen will show you this 
![image](https://github.com/ZoeyVid/NPMplus/assets/81431263/433e20bd-d64c-4b6a-b5f2-0f56346b8cc7)

**Comment by Zoey2936** [comment]
should be fixed in the next release
