### ISSUE TITLE
ip6 to origin 

### ISSUE THREAD

**Issue by hellgod77** [ZoeyVid/NPMplus#704]
it works to the edge not to origin it is host i have spent 2 days messing with it, i make a stream and point the proxy to that it works but connecting directly to it this is all i get 
2024/03/19 07:52:30 [error] 6427#6427: *124 prox6.****o.net could not be resolved (3: Host not found), client: 2600:6c40:****9a00:7c07:****:854f:c3ca, server: tv.***.io, request: "GET / HTTP/3.0"
2024/03/19 07:52:34 [error] 6427#6427: *129 prox6.***.net could not be resolved (3: Host not found), client: 2600:6c40:****:9a00:7c07:****:854f:c3ca, server: tv.***.io, request: "GET /favicon.ico HTTP/3.0", referrer: "https://tv.***.io/"

i have messed with dns nohing and they resolve at cli and like i said it resolves as a stream so i can make that and point it to the wan and it works but thats kinda counterproductive. there is no other modsec or anything on either same result on or off

**Comment by Zoey2936** [comment]
Sorry, but I don't understand your sentence

**Comment by Zoey2936** [comment]
What do you mean?

**Comment by hellgod77** [comment]
sorry try to be more clear, not in a hurry to get to work... i am using the proxy to connect to ip6 only origins, and it wont work it says bad gateway, if i how ever make a stream host like 8096 to ip6 domain 8096 and point the proxy to its own wan address then it works, the logs act like it's not resolving dns, but it is and it's the same error if i just use the ip address, so i know it works because it works by making a stream first and i should not need to i didn't on the original npm. its running host and it's the only thing other than portainer running so there's no conflicts, i have tried making it a not host, i have tried changing to privileged and all kinds of crap same result I'm stuck it done it on Debian and centos.

**Comment by hellgod77** [comment]
im still new to docker, but instead of using host how would i bind it to a interface?, the host also have a internal non routable ip6 and i wonder if its picking that up on host

**Comment by Zoey2936** [comment]
Does `docker exec npmplus curl -6kL http(s)://<domain>` work?

**Comment by hellgod77** [comment]
yes, but it still when you load a page its bad gateway and it only works as a stream with the proxy pointed to the stream i have tried 5 linux distros all the same thing the old npm works fine

**Comment by hellgod77** [comment]
it's like ngix can't resolve it for some reason, like it has its own dns lookup other than the host i have no idea, but when it fails the logs say error 3 unable to resolve.

**Comment by hellgod77** [comment]
or a issue with the version of docker I'm using but its the official one from them not the pod or snap one

**Comment by Zoey2936** [comment]
And direct ipv6 does not work?

**Comment by hellgod77** [comment]
not from npm no it says can't be resolved in the docker logs, but it is because it resolves as a stream or curl or by ping from the host.

**Comment by Zoey2936** [comment]
Should be fixed in the develop tag, please try it. If it works, I will release it later today

**Comment by Zoey2936** [comment]
@hellgod77 can you please tets it?

**Comment by hellgod77** [comment]
define direct it does from the host not npm
________________________________

**Comment by hellgod77** [comment]
let me see if i can figure out how, thank you

________________________________

**Comment by Zoey2936** [comment]
just add `:develop` to the image name, so it looks like this: `zoeyvid/npmplus:develop`

**Comment by hellgod77** [comment]
doing as we speak
________________________________

**Comment by hellgod77** [comment]
yay it works now what was it i was  pulling my hair out
________________________________

**Comment by Zoey2936** [comment]
Now published to latest

**Comment by hellgod77** [comment]
i meant to tell you i have paid version of GitHub with all the code space stuff, if you need access to it you can i have no idea what im doing in it i just got it because it linked with azure and i was curious
________________________________

**Comment by Zoey2936** [comment]
Thanks, but I don't need it
