### ISSUE TITLE
Certificate stapling not working

### ISSUE THREAD

**Issue by YeapGuy** [ZoeyVid/NPMplus#714]
When loading any of the hosts provided by NPMplus, I get the following error on Firefox:
![image](https://github.com/ZoeyVid/NPMplus/assets/43749899/aad2abf7-6f86-41c2-9cff-4f11fd9727c8)
Looking it up, it seems to be related to stapling of certificates. The original NPM didn't do this, so I didn't have that issue with my migrated certificates. Now that I generated new certificates in NPMplus, this happens.
**Strangely, reloading the page fixes it, and it loads properly.** Still, I need my pages to load on first attempt. 😄 

A public page you can test this on: https://panel.ascend.host Hopefully, you can replicate.

**Comment by Zoey2936** [comment]
sorry, but I can't reproduce
but you can try to disable must-staple in /opt/npm/tls/certbot/config.ini and then recreate (not renew) your certs and retry

**Comment by YeapGuy** [comment]
Too bad. Okay, I'll disable stapling.
