### ISSUE TITLE
GoAccess Issue

### ISSUE THREAD

**Issue by Johannp02180** [ZoeyVid/NPMplus#782]
Love NPMplus so far, just moved over from NPM. In goaccess, I'm unable to see the real ips. I'm using bridge mode for docker as I'm using a cloudflare tunnel only. In the past with my other instance in bridge mode and goaccess, I'm able to get real ips as well, I'm not sure if I misconfigured something.Thank you!

<img width="705" alt="Screenshot 2024-04-25 at 3 38 19 AM" src="https://github.com/ZoeyVid/NPMplus/assets/11222092/41345917-e371-4285-a770-a3460623acbd">

**Comment by Johannp02180** [comment]
Duplicate sorry my network timed out

**Comment by Zoey2936** [comment]
Does cloudflare sent you a real ip header?

**Comment by Johannp02180** [comment]
Is this something I should be able to find in inspect element networking?

**Comment by Zoey2936** [comment]
nginx replaces the ip, which connects to nginx (cloudflareds ip), with the ip of the real ip header, if cloudflared sends this header and the ip of clouflared (not the header) is a local ip

**Comment by Johannp02180** [comment]
Ok update, if I include the following in the advanced section it works `real_ip_header CF-Connecting-IP;`
However what is the best way to apply this across all the proxies? I saw in each proxy host, it calls the empty server_proxy.conf file so I added it there, but it doesn't work.

**Comment by Johannp02180** [comment]
Okay I see that file isn't in the location block, is there a file mapped already that I can add it to that's inside the location / block?

**Comment by Zoey2936** [comment]
yes, Cloudflare seems to send a CF-Connecting-IP instead of an X-Real-IP header, I will try to fix this in the next release

**Comment by Zoey2936** [comment]
should be fixed now

**Comment by Zoey2936** [comment]
please report back if the latest release fixed it

**Comment by Zoey2936** [comment]
does it work now for you?

**Comment by Johannp02180** [comment]
I’ll try it in the morning and report back! Thanks

**Comment by Johannp02180** [comment]
Yup its working now thanks! No extra header from me is needed and I can see that the correct IP in access.log
