### ISSUE TITLE
Incorrect path to index.html

### ISSUE THREAD

**Issue by vrelk** [ZoeyVid/NPMplus#861]
Using the latest docker image as of 6/2/2024, if you try to set a custom page for the default site, you are presented with an error.

The docker logs return the following:
`[Express  ] › ⚠  warning   ENOENT: no such file or directory, open '/data/nginx/etc/index.html'`

The correct path to this file based on the current directory layout is `/data/etc/html/index.html`

**Comment by Zoey2936** [comment]
https://github.com/ZoeyVid/NPMplus/blob/71e8993503e9299bdc4883e9854c3166119bb594/backend/templates/default.conf#L57 it should work

**Comment by Zoey2936** [comment]
can you recreate the default host?

**Comment by vrelk** [comment]
This is the one I'm looking at.
https://github.com/ZoeyVid/NPMplus/blob/7e1f800f6649fa1236054834cb6a07edc7f9e017/backend/internal/setting.js#L36

`/data/nginx/etc/` doesn't exist, but `/data/etc/html/` does, and contains an empty index.html file. I'm thinking that either the line referenced above is pointing to the incorrect location, or an `etc` folder needs to be added to `/data/nginx/`.
![image](https://github.com/ZoeyVid/NPMplus/assets/626365/c860a147-a9a4-4e24-86aa-c5a7dc9cb2ac)
