### ISSUE TITLE
CLean Install - no login

### ISSUE THREAD

**Issue by stanthewizzard** [ZoeyVid/NPMplus#928]
Hello

After Clean install 2024-07-01-r1.
Impossible to login with 
Email:    admin@example.com
Password: iArhP1j7p1P6TA92FA2FMbbUGYqwcYzxC4AVEe12Wbi94FY9gNN62aKyF1shrvG4NycjjX9KfmDQiwkLZH1ZDR9xMjiG2QmoHXi

Internal Error

Thanks

**Comment by Zoey2936** [comment]
See #926

**Comment by stanthewizzard** [comment]
sorry thanks
