### ISSUE TITLE
Using a Proxy Host entry for NPMplus Web UI Issue

### ISSUE THREAD

**Issue by nealhead** [ZoeyVid/NPMplus#942]
I tried setting up a proxy host to reach NPMplus by fqdn locally with a wildcart certificate is not working as intended as it did with NPM.

When I enter the URL, it attempts to redirect to port 81. If I append /login to the URL I can reach the login page but when I try to login it again tries to redirect to port 81.

It doesn't seem to be generating a log for this. 

Version: 2.11.2+454f3aa

**Comment by nealhead** [comment]
I may have solved this myself... by using Custom Location and setting to /nginx

**Comment by Zoey2936** [comment]
You need to use https as sheme
