### ISSUE TITLE
stream port ranges not supported?

### ISSUE THREAD

**Issue by gadget78** [ZoeyVid/NPMplus#945]
this has been brought up in the NPM github issues here .. 
https://github.com/NginxProxyManager/nginx-proxy-manager/issues/1969

were we are not able to state a range for the streams to use, 
and nginx is able to support them natively as pointed out in the nginx native docs .. 
https://nginx.org/en/docs/stream/ngx_stream_core_module.html#listen

i actually need this support in the API as well, as i m trying to populate the streams via API 
i initially thought it was a API issue, but then realized it was a actual NPM issue.

**Comment by Zoey2936** [comment]
Hello, I will allow this in a few days.

Todo:
- write migration to change this from integer to a string: https://github.com/ZoeyVid/NPMplus/blob/612b16b113ca5d56a86ad1bb7399b50a3bce26db/backend/migrations/20180618015850_initial.js#L126
- ~~knex config to better-sqlite3 https://github.com/ZoeyVid/NPMplus/blob/develop/backend/lib/config.js~~
- ~~better-sqlite3 bin check~~
- rewrite better-sqlite3 (vacuum/password change)

**Comment by gadget78** [comment]
thats awesome thankyou for prompt reply, with a solution for near future !
will be on standby ready to test

**Comment by Zoey2936** [comment]
will be released in a few hours

**Comment by gadget78** [comment]
this works fantastically :) and via the API too, thankyou .... 

i know this is closed topic now, as post is now fixed,
and i know this question is more of "how nginx works ... "
just im having trouble pin pointing an answer .. 

so now we have port ranges in streams,
so we can now set "Incoming Port" to, lets say 1000-10010 for an example.. 
and we set "Forward Port" to 1000
does ALL traffic from those 10 ports all get funnelled into that single port of 1000 ? 
or does it "map" so traffic at port 1002, gets forwarded port of 1002 ? 

and if not, is there a method that can enable this ? like some form of directive within any form of custom mapping ? 

or would i need to map each port individually ?

**Comment by Zoey2936** [comment]
sorry, no idea, I don't use streams, they just exist because of upstream
