### ISSUE TITLE
running php as non-root does not work

### ISSUE THREAD

**Issue by realies** [ZoeyVid/NPMplus#958]
when PUID/PGID are set, starting up ends up here:
```
...
npmplus  | Working on file: /data/nginx/proxy_host/8.conf
npmplus  | Success.
npmplus  | chown: cannot access '/proc/self/fd/3': No such file or directory
npmplus  | chown: cannot access '/proc/self/fd/4': No such file or directory
npmplus  | chown: cannot access '/proc/self/fd/5': No such file or directory
```

i think it's worth trying to output to `/dev/stdout` and alike vs `/proc/self/fd/1`, but i'm not sure if it's a fix
ref: https://github.com/realies/soulseek-docker/issues/88#issuecomment-2081563596

**Comment by Zoey2936** [comment]
hello this is just a warning, you can ignore it

**Comment by realies** [comment]
that's right! it just too significantly longer to start the server for some reason, could it be the chown step?

**Comment by Zoey2936** [comment]
yes it is the chown step
