### ISSUE TITLE
Migration help

### ISSUE THREAD

**Issue by Giuseppe-TD** [ZoeyVid/NPMplus#963]
I can't get the migration from npm work, 
I'm running npm in portainer and I want to migrate to nmpplus, but I cant find how to make it work.
I read the migration, but don't underestand how to migrate.
I have to create a new stack and point to the opt/npm folder? Or i have to modify the npm stack and change the image pull? With other addiction of data folder ?

**Comment by Zoey2936** [comment]
can you show me your current compose file?
