### ISSUE TITLE
owner is null

### ISSUE THREAD

**Issue by musgos** [ZoeyVid/NPMplus#965]
after deleting admin user can´t see anything. 
All is "owner is 
![image](https://github.com/user-attachments/assets/206da4d0-db69-401b-bc9c-3f046a3b4114)

**Comment by Zoey2936** [comment]
so this happens if you delete the user, which created the host?

**Comment by musgos** [comment]
create 2 new admin users, log off, login with new user, delete admin user. log off -> login and "owner is null"
i think it is because in DB the creator of the proxy hosts was admin, but i'm guessing

**Comment by musgos** [comment]
> so this happens if you delete the user, which created the host?

yes, probably

**Comment by musgos** [comment]
If i create a new proxy host, cant see it in the list (same message) , but it i apply a filter (in search host...) it will appear, then gone after removal of filter

PS every proxy is working normal

**Comment by JSouthGB** [comment]
I suspect this is related to an upstream issue. If it is, connecting to the db and changing the `is_deleted` flag to `0` would correct it. Or maybe needing to change the unique id to 1.

For reference, NginxProxyManager/nginx-proxy-manager#230 - [my findings](https://github.com/NginxProxyManager/nginx-proxy-manager/issues/230#issuecomment-1545035684)

**Comment by Zoey2936** [comment]
I must say, I think I can't fix this, but PR are welcome (you can also create one in upstream). Otherwise it should workl in the php version (in the future), since in the first time there will be no multiple user support

**Comment by JSouthGB** [comment]
> I must say, I think I can't fix this, but PR are welcome (you can also create one in upstream). Otherwise it should workl in the php version (in the future), since in the first time there will be no multiple user support

Due to issues like this as well as others, I've moved on from NPM. I had tried this fork, but found some upstream issues still present. Also, I've never implemented multiple users in NPM, but these issues still occurred. Once the rewrite is complete, I'll probably circle back to check it out.

I'm also nowhere near knowledgeable enough to even begin opening a PR.

**Comment by Zoey2936** [comment]
there is PR in upstream: https://github.com/NginxProxyManager/nginx-proxy-manager/pull/4166/files

**Comment by JSouthGB** [comment]
> there is PR in upstream: https://github.com/NginxProxyManager/nginx-proxy-manager/pull/4166/files

Great news! Looks like it was a fairly straightforward fix.

**Comment by Zoey2936** [comment]
can you please try the develop tag if this fixes it?
