### ISSUE TITLE
Error when configuring proxy_host advanced tab

### ISSUE THREAD

**Issue by signo1337** [ZoeyVid/NPMplus#984]
Hey there

Sorry, had no option to reopen the issue I opened before. After completely setting up npmplus afresh (deleting all data) and using the linked config for the advanced tab in proxy_host, i still get a similar error when hovering over "Offline". And the same errors when checking the logs. 
![image](https://github.com/user-attachments/assets/5fcc1b7c-0b22-47af-8d7a-a62d88485719)
[Nginx    ] › ℹ  info      Reloading Nginx
[Nginx    ] › ⬤  debug     Deleting file: /data/nginx/proxy_host/2.conf
[Nginx    ] › ⬤  debug     Could not delete file: {
  "errno": -2,
  "code": "ENOENT",
  "syscall": "unlink",
  "path": "/data/nginx/proxy_host/2.conf"
}
[Nginx    ] › ⬤  debug     Deleting file: /data/nginx/proxy_host/2.conf
[Nginx    ] › ⬤  debug     Deleting file: /data/nginx/proxy_host/2.conf.err
[Nginx    ] › ⬤  debug     Could not delete file: {
  "errno": -2,
  "code": "ENOENT",
  "syscall": "unlink",
  "path": "/data/nginx/proxy_host/2.conf.err"
}
[Nginx    ] › ℹ  info      Reloading Nginx

Any further ideas? What would be the npmplus container that resembles npm 2.10.4? i might give that a chance... thanks.

**Comment by Zoey2936** [comment]
I fixed my answer in the discussion
