### ISSUE TITLE
[Error] ERRNO -2 / Forwarding to Authentik not working

### ISSUE THREAD

**Issue by signo1337** [ZoeyVid/NPMplus#998]
Hey there

After having things successfully set up last week, it seems some forwarding to Authentik is broken.

This is the advanced config I am using, as per the respective, solved issue:

`port_in_redirect off; location / { include conf.d/include/always.conf; proxy_set_header Upgrade $http_upgrade; proxy_set_header Connection $connection_upgrade; include conf.d/include/proxy.conf; auth_request /outpost.goauthentik.io/auth/nginx; error_page 401 = @goauthentik_proxy_signin; auth_request_set $auth_cookie $upstream_http_set_cookie; more_set_headers 'Set-Cookie: $auth_cookie'; auth_request_set $authentik_username $upstream_http_x_authentik_username; auth_request_set $authentik_groups $upstream_http_x_authentik_groups; auth_request_set $authentik_email $upstream_http_x_authentik_email; auth_request_set $authentik_name $upstream_http_x_authentik_name; auth_request_set $authentik_uid $upstream_http_x_authentik_uid; proxy_set_header X-authentik-username $authentik_username; proxy_set_header X-authentik-groups $authentik_groups; proxy_set_header X-authentik-email $authentik_email; proxy_set_header X-authentik-name $authentik_name; proxy_set_header X-authentik-uid $authentik_uid; } location /outpost.goauthentik.io { proxy_set_header Upgrade $http_upgrade; proxy_set_header Connection $connection_upgrade; include conf.d/include/proxy-location.conf; proxy_pass https://<ip>:9443/outpost.goauthentik.io; # ensure the host of this vserver matches your external URL you've configured in authentik proxy_set_header X-Original-URL $scheme://$host$request_uri; more_set_headers 'Set-Cookie: $auth_cookie'; auth_request_set $auth_cookie $upstream_http_set_cookie; proxy_pass_request_body off; proxy_set_header Content-Length ""; } location @goauthentik_proxy_signin { internal; more_set_headers 'Set-Cookie: $auth_cookie'; return 302 /outpost.goauthentik.io/start?rd=$request_uri; }`

Flow goes like this:

NPMPlus > Authentik > Synology Photos, with the respective regex exceptions for the authentication path in Authentik, in order to bypass authentication on mobile apps. This has worked perfectly fine last week.

But now when trying to log in on the mobile app, I get Error number -2, which probably is not a Synology error code. Instead, it shows up in the NPMPlus logs like this:

![Screenshot_20240804-183915_Iceraven_1.png](https://github.com/user-attachments/assets/87043d59-d20c-4cb1-9887-11513a696c29)

Do you have any idea what could cause this? Maybe with regards to changes in the recent update?

Deleting the advanced config makes the login work flawlessly, but then ofc without the additional security layer from Authentik.

Thanks in advance.

Best

**Comment by Zoey2936** [comment]
please keep authetic in the authentic thread
