### ISSUE TITLE
some question regardin modsecurity

### ISSUE THREAD

**Issue by Giuseppe-TD** [ZoeyVid/NPMplus#999]
i'm running multiple sites based on joomla with npm plus ( before was the npm standard)
i upgraded to npm plus 2 weeks ago ( i already posted some issues)
now i have a couple of question regarding modsecurity and some adjustemd i had to do in the modsecurity-default.config to let my websites working ( at least to modify in the backend)
- i had to edit the lines (adding some 0 at end):
SecRequestBodyLimit 1310720000000
SecRequestBodyNoFilesLimit 1310720000000
SecArgumentsLimit 1000000
SecRule &ARGS "@ge 1000000" \

if the lines was at default i can't edit in the backend of my websites

[file "/data/etc/modsecurity/modsecurity-default.conf"] [line "67"] [id "200007"] [rev ""] [msg "Failed to fully parse request body due to large argument count"] [data ""] [severity "2"] [ver ""] [maturity "0"] [accuracy "0"] [hostname "10.1.1.245"] [uri "/administrator/index.php"] [unique_id "172296146270.157715"]

this is the error i get 

so the question is.. modify the lines can harm the security ?

**Comment by Zoey2936** [comment]
it could make a lot cpu usage, if it needs to parse big files
